/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ExecutionType the model 'ExecutionType'
type ExecutionType string

// List of ExecutionType
const (
	MARKET ExecutionType = "market"
	LIMIT ExecutionType = "limit"
)

func (v *ExecutionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExecutionType(value)
	for _, existing := range []ExecutionType{ "market", "limit",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExecutionType", value)
}

// Ptr returns reference to ExecutionType value
func (v ExecutionType) Ptr() *ExecutionType {
	return &v
}

type NullableExecutionType struct {
	value *ExecutionType
	isSet bool
}

func (v NullableExecutionType) Get() *ExecutionType {
	return v.value
}

func (v *NullableExecutionType) Set(val *ExecutionType) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionType) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionType(val *ExecutionType) *NullableExecutionType {
	return &NullableExecutionType{value: val, isSet: true}
}

func (v NullableExecutionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

