/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSecurityAccountsResponseUserTradePermissionVOs struct for GetSecurityAccountsResponseUserTradePermissionVOs
type GetSecurityAccountsResponseUserTradePermissionVOs struct {
	HasPermission *bool `json:"hasPermission,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewGetSecurityAccountsResponseUserTradePermissionVOs instantiates a new GetSecurityAccountsResponseUserTradePermissionVOs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecurityAccountsResponseUserTradePermissionVOs() *GetSecurityAccountsResponseUserTradePermissionVOs {
	this := GetSecurityAccountsResponseUserTradePermissionVOs{}
	return &this
}

// NewGetSecurityAccountsResponseUserTradePermissionVOsWithDefaults instantiates a new GetSecurityAccountsResponseUserTradePermissionVOs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecurityAccountsResponseUserTradePermissionVOsWithDefaults() *GetSecurityAccountsResponseUserTradePermissionVOs {
	this := GetSecurityAccountsResponseUserTradePermissionVOs{}
	return &this
}

// GetHasPermission returns the HasPermission field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) GetHasPermission() bool {
	if o == nil || o.HasPermission == nil {
		var ret bool
		return ret
	}
	return *o.HasPermission
}

// GetHasPermissionOk returns a tuple with the HasPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) GetHasPermissionOk() (*bool, bool) {
	if o == nil || o.HasPermission == nil {
		return nil, false
	}
	return o.HasPermission, true
}

// HasHasPermission returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) HasHasPermission() bool {
	if o != nil && o.HasPermission != nil {
		return true
	}

	return false
}

// SetHasPermission gets a reference to the given bool and assigns it to the HasPermission field.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) SetHasPermission(v bool) {
	o.HasPermission = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetSecurityAccountsResponseUserTradePermissionVOs) SetType(v string) {
	o.Type = &v
}

func (o GetSecurityAccountsResponseUserTradePermissionVOs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.HasPermission != nil {
		toSerialize["hasPermission"] = o.HasPermission
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableGetSecurityAccountsResponseUserTradePermissionVOs struct {
	value *GetSecurityAccountsResponseUserTradePermissionVOs
	isSet bool
}

func (v NullableGetSecurityAccountsResponseUserTradePermissionVOs) Get() *GetSecurityAccountsResponseUserTradePermissionVOs {
	return v.value
}

func (v *NullableGetSecurityAccountsResponseUserTradePermissionVOs) Set(val *GetSecurityAccountsResponseUserTradePermissionVOs) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecurityAccountsResponseUserTradePermissionVOs) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecurityAccountsResponseUserTradePermissionVOs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecurityAccountsResponseUserTradePermissionVOs(val *GetSecurityAccountsResponseUserTradePermissionVOs) *NullableGetSecurityAccountsResponseUserTradePermissionVOs {
	return &NullableGetSecurityAccountsResponseUserTradePermissionVOs{value: val, isSet: true}
}

func (v NullableGetSecurityAccountsResponseUserTradePermissionVOs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecurityAccountsResponseUserTradePermissionVOs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


