/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetOptionQuotesRequest struct for GetOptionQuotesRequest
type GetOptionQuotesRequest struct {
	DerivativeIds float32 `json:"derivativeIds,omitempty"`
	// tickerId
	TickerId float32 `json:"tickerId,omitempty"`
}
