/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetFundamentalsResponseForecast struct for GetFundamentalsResponseForecast
type GetFundamentalsResponseForecast struct {
	Data *GetFundamentalsResponseData `json:"data,omitempty"`
	ReportType *int32 `json:"reportType,omitempty"`
	StatementType *int32 `json:"statementType,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewGetFundamentalsResponseForecast instantiates a new GetFundamentalsResponseForecast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFundamentalsResponseForecast() *GetFundamentalsResponseForecast {
	this := GetFundamentalsResponseForecast{}
	return &this
}

// NewGetFundamentalsResponseForecastWithDefaults instantiates a new GetFundamentalsResponseForecast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFundamentalsResponseForecastWithDefaults() *GetFundamentalsResponseForecast {
	this := GetFundamentalsResponseForecast{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecast) GetData() GetFundamentalsResponseData {
	if o == nil || o.Data == nil {
		var ret GetFundamentalsResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecast) GetDataOk() (*GetFundamentalsResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecast) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetFundamentalsResponseData and assigns it to the Data field.
func (o *GetFundamentalsResponseForecast) SetData(v GetFundamentalsResponseData) {
	o.Data = &v
}

// GetReportType returns the ReportType field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecast) GetReportType() int32 {
	if o == nil || o.ReportType == nil {
		var ret int32
		return ret
	}
	return *o.ReportType
}

// GetReportTypeOk returns a tuple with the ReportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecast) GetReportTypeOk() (*int32, bool) {
	if o == nil || o.ReportType == nil {
		return nil, false
	}
	return o.ReportType, true
}

// HasReportType returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecast) HasReportType() bool {
	if o != nil && o.ReportType != nil {
		return true
	}

	return false
}

// SetReportType gets a reference to the given int32 and assigns it to the ReportType field.
func (o *GetFundamentalsResponseForecast) SetReportType(v int32) {
	o.ReportType = &v
}

// GetStatementType returns the StatementType field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecast) GetStatementType() int32 {
	if o == nil || o.StatementType == nil {
		var ret int32
		return ret
	}
	return *o.StatementType
}

// GetStatementTypeOk returns a tuple with the StatementType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecast) GetStatementTypeOk() (*int32, bool) {
	if o == nil || o.StatementType == nil {
		return nil, false
	}
	return o.StatementType, true
}

// HasStatementType returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecast) HasStatementType() bool {
	if o != nil && o.StatementType != nil {
		return true
	}

	return false
}

// SetStatementType gets a reference to the given int32 and assigns it to the StatementType field.
func (o *GetFundamentalsResponseForecast) SetStatementType(v int32) {
	o.StatementType = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetFundamentalsResponseForecast) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseForecast) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetFundamentalsResponseForecast) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetFundamentalsResponseForecast) SetTitle(v string) {
	o.Title = &v
}

func (o GetFundamentalsResponseForecast) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.ReportType != nil {
		toSerialize["reportType"] = o.ReportType
	}
	if o.StatementType != nil {
		toSerialize["statementType"] = o.StatementType
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableGetFundamentalsResponseForecast struct {
	value *GetFundamentalsResponseForecast
	isSet bool
}

func (v NullableGetFundamentalsResponseForecast) Get() *GetFundamentalsResponseForecast {
	return v.value
}

func (v *NullableGetFundamentalsResponseForecast) Set(val *GetFundamentalsResponseForecast) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFundamentalsResponseForecast) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFundamentalsResponseForecast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFundamentalsResponseForecast(val *GetFundamentalsResponseForecast) *NullableGetFundamentalsResponseForecast {
	return &NullableGetFundamentalsResponseForecast{value: val, isSet: true}
}

func (v NullableGetFundamentalsResponseForecast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFundamentalsResponseForecast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


