/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrderSide the model 'OrderSide'
type OrderSide string

// List of OrderSide
const (
	BUY OrderSide = "BUY"
	SELL OrderSide = "SELL"
)

func (v *OrderSide) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderSide(value)
	for _, existing := range []OrderSide{ "BUY", "SELL",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderSide", value)
}

// Ptr returns reference to OrderSide value
func (v OrderSide) Ptr() *OrderSide {
	return &v
}

type NullableOrderSide struct {
	value *OrderSide
	isSet bool
}

func (v NullableOrderSide) Get() *OrderSide {
	return v.value
}

func (v *NullableOrderSide) Set(val *OrderSide) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderSide) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderSide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderSide(val *OrderSide) *NullableOrderSide {
	return &NullableOrderSide{value: val, isSet: true}
}

func (v NullableOrderSide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderSide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

