/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetActiveGainersLosersResponse struct for GetActiveGainersLosersResponse
type GetActiveGainersLosersResponse struct {
	Items GetActiveGainersLosersResponseItems `json:"items,omitempty"`
}
