/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetSecurityAccountsResponseTimeInForces struct for GetSecurityAccountsResponseTimeInForces
type GetSecurityAccountsResponseTimeInForces struct {
	Name string `json:"name,omitempty"`
	Alias string `json:"alias,omitempty"`
}
