/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetStockAnalysisResponse struct for GetStockAnalysisResponse
type GetStockAnalysisResponse struct {
	ForecastEps GetFundamentalsResponseData `json:"forecastEps,omitempty"`
	Rating GetStockAnalysisResponseRating `json:"rating,omitempty"`
	TargetPrice GetStockAnalysisResponseTargetPrice `json:"targetPrice,omitempty"`
}
