/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetStockAnalysisResponseTargetPrice struct for GetStockAnalysisResponseTargetPrice
type GetStockAnalysisResponseTargetPrice struct {
	Low string `json:"low,omitempty"`
	High string `json:"high,omitempty"`
	Current string `json:"current,omitempty"`
	Mean string `json:"mean,omitempty"`
}
