/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetSecurityAccountsResponseData struct for GetSecurityAccountsResponseData
type GetSecurityAccountsResponseData struct {
	SecAccountId float32 `json:"secAccountId,omitempty"`
	RegisterRegionId float32 `json:"registerRegionId,omitempty"`
	BrokerId float32 `json:"brokerId,omitempty"`
	BrokerName string `json:"brokerName,omitempty"`
	BrokerAccountId string `json:"brokerAccountId,omitempty"`
	Status string `json:"status,omitempty"`
	RegisterTradeUrl string `json:"registerTradeUrl,omitempty"`
	OpenAccountUrl string `json:"openAccountUrl,omitempty"`
	SupportOutsideRth bool `json:"supportOutsideRth,omitempty"`
	TickerTypes []GetSecurityAccountsResponseTickerTypes `json:"tickerTypes,omitempty"`
	AccountTypes []string `json:"accountTypes,omitempty"`
	UserTradePermissionVOs []GetSecurityAccountsResponseUserTradePermissionVOs `json:"userTradePermissionVOs,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	Deposit bool `json:"deposit,omitempty"`
	AllowDeposit bool `json:"allowDeposit,omitempty"`
	CustomerType string `json:"customerType,omitempty"`
	GiftStockStatus float32 `json:"giftStockStatus,omitempty"`
	DepositStatus string `json:"depositStatus,omitempty"`
	TimeInForces []GetSecurityAccountsResponseTimeInForces `json:"timeInForces,omitempty"`
	ComboTypes []string `json:"comboTypes,omitempty"`
	SupportClickIPO bool `json:"supportClickIPO,omitempty"`
	IsDefaultChecked bool `json:"isDefaultChecked,omitempty"`
	OptionOpenStatus string `json:"optionOpenStatus,omitempty"`
	SupportOpenOption bool `json:"supportOpenOption,omitempty"`
}
