/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostOtocoOrderRequest struct for PostOtocoOrderRequest
type PostOtocoOrderRequest struct {
	NewOrders *[]PostStockOrderRequest `json:"newOrders,omitempty"`
}

// NewPostOtocoOrderRequest instantiates a new PostOtocoOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostOtocoOrderRequest() *PostOtocoOrderRequest {
	this := PostOtocoOrderRequest{}
	return &this
}

// NewPostOtocoOrderRequestWithDefaults instantiates a new PostOtocoOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostOtocoOrderRequestWithDefaults() *PostOtocoOrderRequest {
	this := PostOtocoOrderRequest{}
	return &this
}

// GetNewOrders returns the NewOrders field value if set, zero value otherwise.
func (o *PostOtocoOrderRequest) GetNewOrders() []PostStockOrderRequest {
	if o == nil || o.NewOrders == nil {
		var ret []PostStockOrderRequest
		return ret
	}
	return *o.NewOrders
}

// GetNewOrdersOk returns a tuple with the NewOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostOtocoOrderRequest) GetNewOrdersOk() (*[]PostStockOrderRequest, bool) {
	if o == nil || o.NewOrders == nil {
		return nil, false
	}
	return o.NewOrders, true
}

// HasNewOrders returns a boolean if a field has been set.
func (o *PostOtocoOrderRequest) HasNewOrders() bool {
	if o != nil && o.NewOrders != nil {
		return true
	}

	return false
}

// SetNewOrders gets a reference to the given []PostStockOrderRequest and assigns it to the NewOrders field.
func (o *PostOtocoOrderRequest) SetNewOrders(v []PostStockOrderRequest) {
	o.NewOrders = &v
}

func (o PostOtocoOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NewOrders != nil {
		toSerialize["newOrders"] = o.NewOrders
	}
	return json.Marshal(toSerialize)
}

type NullablePostOtocoOrderRequest struct {
	value *PostOtocoOrderRequest
	isSet bool
}

func (v NullablePostOtocoOrderRequest) Get() *PostOtocoOrderRequest {
	return v.value
}

func (v *NullablePostOtocoOrderRequest) Set(val *PostOtocoOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostOtocoOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostOtocoOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostOtocoOrderRequest(val *PostOtocoOrderRequest) *NullablePostOtocoOrderRequest {
	return &NullablePostOtocoOrderRequest{value: val, isSet: true}
}

func (v NullablePostOtocoOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostOtocoOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


