/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostOtocoStockOrderRequest struct for PostOtocoStockOrderRequest
type PostOtocoStockOrderRequest struct {
	Action OrderSide `json:"action,omitempty"`
	// limit price
	LmtPrice string `json:"lmtPrice,omitempty"`
	OrderType OrderType `json:"orderType,omitempty"`
	OutsideRegularTradingHour bool `json:"outsideRegularTradingHour,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
	SerialId string `json:"serialId,omitempty"`
	TickerId float32 `json:"tickerId,omitempty"`
	TimeInForce string `json:"timeInForce,omitempty"`
}
