/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSecurityAccountsResponseTickerTypes struct for GetSecurityAccountsResponseTickerTypes
type GetSecurityAccountsResponseTickerTypes struct {
	OrderTypes *[]OrderType `json:"orderTypes,omitempty"`
	RegionId *int32 `json:"regionId,omitempty"`
	TickerType *int32 `json:"tickerType,omitempty"`
}

// NewGetSecurityAccountsResponseTickerTypes instantiates a new GetSecurityAccountsResponseTickerTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecurityAccountsResponseTickerTypes() *GetSecurityAccountsResponseTickerTypes {
	this := GetSecurityAccountsResponseTickerTypes{}
	return &this
}

// NewGetSecurityAccountsResponseTickerTypesWithDefaults instantiates a new GetSecurityAccountsResponseTickerTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecurityAccountsResponseTickerTypesWithDefaults() *GetSecurityAccountsResponseTickerTypes {
	this := GetSecurityAccountsResponseTickerTypes{}
	return &this
}

// GetOrderTypes returns the OrderTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseTickerTypes) GetOrderTypes() []OrderType {
	if o == nil || o.OrderTypes == nil {
		var ret []OrderType
		return ret
	}
	return *o.OrderTypes
}

// GetOrderTypesOk returns a tuple with the OrderTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseTickerTypes) GetOrderTypesOk() (*[]OrderType, bool) {
	if o == nil || o.OrderTypes == nil {
		return nil, false
	}
	return o.OrderTypes, true
}

// HasOrderTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseTickerTypes) HasOrderTypes() bool {
	if o != nil && o.OrderTypes != nil {
		return true
	}

	return false
}

// SetOrderTypes gets a reference to the given []OrderType and assigns it to the OrderTypes field.
func (o *GetSecurityAccountsResponseTickerTypes) SetOrderTypes(v []OrderType) {
	o.OrderTypes = &v
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseTickerTypes) GetRegionId() int32 {
	if o == nil || o.RegionId == nil {
		var ret int32
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseTickerTypes) GetRegionIdOk() (*int32, bool) {
	if o == nil || o.RegionId == nil {
		return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseTickerTypes) HasRegionId() bool {
	if o != nil && o.RegionId != nil {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given int32 and assigns it to the RegionId field.
func (o *GetSecurityAccountsResponseTickerTypes) SetRegionId(v int32) {
	o.RegionId = &v
}

// GetTickerType returns the TickerType field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseTickerTypes) GetTickerType() int32 {
	if o == nil || o.TickerType == nil {
		var ret int32
		return ret
	}
	return *o.TickerType
}

// GetTickerTypeOk returns a tuple with the TickerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseTickerTypes) GetTickerTypeOk() (*int32, bool) {
	if o == nil || o.TickerType == nil {
		return nil, false
	}
	return o.TickerType, true
}

// HasTickerType returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseTickerTypes) HasTickerType() bool {
	if o != nil && o.TickerType != nil {
		return true
	}

	return false
}

// SetTickerType gets a reference to the given int32 and assigns it to the TickerType field.
func (o *GetSecurityAccountsResponseTickerTypes) SetTickerType(v int32) {
	o.TickerType = &v
}

func (o GetSecurityAccountsResponseTickerTypes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderTypes != nil {
		toSerialize["orderTypes"] = o.OrderTypes
	}
	if o.RegionId != nil {
		toSerialize["regionId"] = o.RegionId
	}
	if o.TickerType != nil {
		toSerialize["tickerType"] = o.TickerType
	}
	return json.Marshal(toSerialize)
}

type NullableGetSecurityAccountsResponseTickerTypes struct {
	value *GetSecurityAccountsResponseTickerTypes
	isSet bool
}

func (v NullableGetSecurityAccountsResponseTickerTypes) Get() *GetSecurityAccountsResponseTickerTypes {
	return v.value
}

func (v *NullableGetSecurityAccountsResponseTickerTypes) Set(val *GetSecurityAccountsResponseTickerTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecurityAccountsResponseTickerTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecurityAccountsResponseTickerTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecurityAccountsResponseTickerTypes(val *GetSecurityAccountsResponseTickerTypes) *NullableGetSecurityAccountsResponseTickerTypes {
	return &NullableGetSecurityAccountsResponseTickerTypes{value: val, isSet: true}
}

func (v NullableGetSecurityAccountsResponseTickerTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecurityAccountsResponseTickerTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


