/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaperTradeAccount struct for PaperTradeAccount
type PaperTradeAccount struct {
	Id int32 `json:"id,omitempty"`
	PaperId int32 `json:"paperId,omitempty"`
	Status int32 `json:"status,omitempty"`
	PaperType int32 `json:"paperType,omitempty"`
	PaperName string `json:"paperName,omitempty"`
	PaperTickerPoolCode string `json:"paperTickerPoolCode,omitempty"`
	Currency string `json:"currency,omitempty"`
	CurrencyId int32 `json:"currencyId,omitempty"`
	SupportOutsideRth bool `json:"supportOutsideRth,omitempty"`
	TimeInForces []string `json:"timeInForces,omitempty"`
	OrderTypes []OrderType `json:"orderTypes,omitempty"`
}
