/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAccountResponsePositions struct for GetAccountResponsePositions
type GetAccountResponsePositions struct {
	Id int32 `json:"id,omitempty"`
	BrokerId int32 `json:"brokerId,omitempty"`
	Ticker GetAccountResponseTicker `json:"ticker,omitempty"`
	Position string `json:"position,omitempty"`
	AssetType string `json:"assetType,omitempty"`
	Cost string `json:"cost,omitempty"`
	CostPrice string `json:"costPrice,omitempty"`
	Currency string `json:"currency,omitempty"`
	LastPrice string `json:"lastPrice,omitempty"`
	MarketValue string `json:"marketValue,omitempty"`
	UnrealizedProfitLoss string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate string `json:"unrealizedProfitLossRate,omitempty"`
	PositionProportion string `json:"positionProportion,omitempty"`
	ExchangeRate string `json:"exchangeRate,omitempty"`
	Lock bool `json:"lock,omitempty"`
	LastOpenTime string `json:"lastOpenTime,omitempty"`
	UpdatePositionTimeStamp int64 `json:"updatePositionTimeStamp,omitempty"`
}
