/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAccountsResponseV5Positions struct for GetAccountsResponseV5Positions
type GetAccountsResponseV5Positions struct {
	PositionId *float32 `json:"positionId,omitempty"`
	BrokerPosId *string `json:"brokerPosId,omitempty"`
	BrokerId *float32 `json:"brokerId,omitempty"`
	AssetType *string `json:"assetType,omitempty"`
	TickerType *string `json:"tickerType,omitempty"`
	Ticker *GetAccountsResponseV5Ticker `json:"ticker,omitempty"`
	Action *string `json:"action,omitempty"`
	Position *string `json:"position,omitempty"`
	TickerId *float32 `json:"tickerId,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	CostPrice *string `json:"costPrice,omitempty"`
	Cost *string `json:"cost,omitempty"`
	Currency *string `json:"currency,omitempty"`
	MarketValue *string `json:"marketValue,omitempty"`
	LastPrice *string `json:"lastPrice,omitempty"`
	UnrealizedProfitLoss *string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate *string `json:"unrealizedProfitLossRate,omitempty"`
	PositionProportion *string `json:"positionProportion,omitempty"`
	UpdatePositionTime *float32 `json:"updatePositionTime,omitempty"`
	OptionCanExercise *float32 `json:"optionCanExercise,omitempty"`
	RecentlyExpireFlag *bool `json:"recentlyExpireFlag,omitempty"`
	RemainDay *float32 `json:"remainDay,omitempty"`
	IsLending *string `json:"isLending,omitempty"`
}

// NewGetAccountsResponseV5Positions instantiates a new GetAccountsResponseV5Positions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountsResponseV5Positions() *GetAccountsResponseV5Positions {
	this := GetAccountsResponseV5Positions{}
	return &this
}

// NewGetAccountsResponseV5PositionsWithDefaults instantiates a new GetAccountsResponseV5Positions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountsResponseV5PositionsWithDefaults() *GetAccountsResponseV5Positions {
	this := GetAccountsResponseV5Positions{}
	return &this
}

// GetPositionId returns the PositionId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetPositionId() float32 {
	if o == nil || o.PositionId == nil {
		var ret float32
		return ret
	}
	return *o.PositionId
}

// GetPositionIdOk returns a tuple with the PositionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetPositionIdOk() (*float32, bool) {
	if o == nil || o.PositionId == nil {
		return nil, false
	}
	return o.PositionId, true
}

// HasPositionId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasPositionId() bool {
	if o != nil && o.PositionId != nil {
		return true
	}

	return false
}

// SetPositionId gets a reference to the given float32 and assigns it to the PositionId field.
func (o *GetAccountsResponseV5Positions) SetPositionId(v float32) {
	o.PositionId = &v
}

// GetBrokerPosId returns the BrokerPosId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetBrokerPosId() string {
	if o == nil || o.BrokerPosId == nil {
		var ret string
		return ret
	}
	return *o.BrokerPosId
}

// GetBrokerPosIdOk returns a tuple with the BrokerPosId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetBrokerPosIdOk() (*string, bool) {
	if o == nil || o.BrokerPosId == nil {
		return nil, false
	}
	return o.BrokerPosId, true
}

// HasBrokerPosId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasBrokerPosId() bool {
	if o != nil && o.BrokerPosId != nil {
		return true
	}

	return false
}

// SetBrokerPosId gets a reference to the given string and assigns it to the BrokerPosId field.
func (o *GetAccountsResponseV5Positions) SetBrokerPosId(v string) {
	o.BrokerPosId = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetBrokerId() float32 {
	if o == nil || o.BrokerId == nil {
		var ret float32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetBrokerIdOk() (*float32, bool) {
	if o == nil || o.BrokerId == nil {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasBrokerId() bool {
	if o != nil && o.BrokerId != nil {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given float32 and assigns it to the BrokerId field.
func (o *GetAccountsResponseV5Positions) SetBrokerId(v float32) {
	o.BrokerId = &v
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetAssetType() string {
	if o == nil || o.AssetType == nil {
		var ret string
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetAssetTypeOk() (*string, bool) {
	if o == nil || o.AssetType == nil {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasAssetType() bool {
	if o != nil && o.AssetType != nil {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given string and assigns it to the AssetType field.
func (o *GetAccountsResponseV5Positions) SetAssetType(v string) {
	o.AssetType = &v
}

// GetTickerType returns the TickerType field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetTickerType() string {
	if o == nil || o.TickerType == nil {
		var ret string
		return ret
	}
	return *o.TickerType
}

// GetTickerTypeOk returns a tuple with the TickerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetTickerTypeOk() (*string, bool) {
	if o == nil || o.TickerType == nil {
		return nil, false
	}
	return o.TickerType, true
}

// HasTickerType returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasTickerType() bool {
	if o != nil && o.TickerType != nil {
		return true
	}

	return false
}

// SetTickerType gets a reference to the given string and assigns it to the TickerType field.
func (o *GetAccountsResponseV5Positions) SetTickerType(v string) {
	o.TickerType = &v
}

// GetTicker returns the Ticker field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetTicker() GetAccountsResponseV5Ticker {
	if o == nil || o.Ticker == nil {
		var ret GetAccountsResponseV5Ticker
		return ret
	}
	return *o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetTickerOk() (*GetAccountsResponseV5Ticker, bool) {
	if o == nil || o.Ticker == nil {
		return nil, false
	}
	return o.Ticker, true
}

// HasTicker returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasTicker() bool {
	if o != nil && o.Ticker != nil {
		return true
	}

	return false
}

// SetTicker gets a reference to the given GetAccountsResponseV5Ticker and assigns it to the Ticker field.
func (o *GetAccountsResponseV5Positions) SetTicker(v GetAccountsResponseV5Ticker) {
	o.Ticker = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *GetAccountsResponseV5Positions) SetAction(v string) {
	o.Action = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetPosition() string {
	if o == nil || o.Position == nil {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetPositionOk() (*string, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *GetAccountsResponseV5Positions) SetPosition(v string) {
	o.Position = &v
}

// GetTickerId returns the TickerId field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetTickerId() float32 {
	if o == nil || o.TickerId == nil {
		var ret float32
		return ret
	}
	return *o.TickerId
}

// GetTickerIdOk returns a tuple with the TickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetTickerIdOk() (*float32, bool) {
	if o == nil || o.TickerId == nil {
		return nil, false
	}
	return o.TickerId, true
}

// HasTickerId returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasTickerId() bool {
	if o != nil && o.TickerId != nil {
		return true
	}

	return false
}

// SetTickerId gets a reference to the given float32 and assigns it to the TickerId field.
func (o *GetAccountsResponseV5Positions) SetTickerId(v float32) {
	o.TickerId = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *GetAccountsResponseV5Positions) SetSymbol(v string) {
	o.Symbol = &v
}

// GetCostPrice returns the CostPrice field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetCostPrice() string {
	if o == nil || o.CostPrice == nil {
		var ret string
		return ret
	}
	return *o.CostPrice
}

// GetCostPriceOk returns a tuple with the CostPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetCostPriceOk() (*string, bool) {
	if o == nil || o.CostPrice == nil {
		return nil, false
	}
	return o.CostPrice, true
}

// HasCostPrice returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasCostPrice() bool {
	if o != nil && o.CostPrice != nil {
		return true
	}

	return false
}

// SetCostPrice gets a reference to the given string and assigns it to the CostPrice field.
func (o *GetAccountsResponseV5Positions) SetCostPrice(v string) {
	o.CostPrice = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetCost() string {
	if o == nil || o.Cost == nil {
		var ret string
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetCostOk() (*string, bool) {
	if o == nil || o.Cost == nil {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasCost() bool {
	if o != nil && o.Cost != nil {
		return true
	}

	return false
}

// SetCost gets a reference to the given string and assigns it to the Cost field.
func (o *GetAccountsResponseV5Positions) SetCost(v string) {
	o.Cost = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetAccountsResponseV5Positions) SetCurrency(v string) {
	o.Currency = &v
}

// GetMarketValue returns the MarketValue field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetMarketValue() string {
	if o == nil || o.MarketValue == nil {
		var ret string
		return ret
	}
	return *o.MarketValue
}

// GetMarketValueOk returns a tuple with the MarketValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetMarketValueOk() (*string, bool) {
	if o == nil || o.MarketValue == nil {
		return nil, false
	}
	return o.MarketValue, true
}

// HasMarketValue returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasMarketValue() bool {
	if o != nil && o.MarketValue != nil {
		return true
	}

	return false
}

// SetMarketValue gets a reference to the given string and assigns it to the MarketValue field.
func (o *GetAccountsResponseV5Positions) SetMarketValue(v string) {
	o.MarketValue = &v
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetLastPrice() string {
	if o == nil || o.LastPrice == nil {
		var ret string
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetLastPriceOk() (*string, bool) {
	if o == nil || o.LastPrice == nil {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasLastPrice() bool {
	if o != nil && o.LastPrice != nil {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given string and assigns it to the LastPrice field.
func (o *GetAccountsResponseV5Positions) SetLastPrice(v string) {
	o.LastPrice = &v
}

// GetUnrealizedProfitLoss returns the UnrealizedProfitLoss field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetUnrealizedProfitLoss() string {
	if o == nil || o.UnrealizedProfitLoss == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLoss
}

// GetUnrealizedProfitLossOk returns a tuple with the UnrealizedProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetUnrealizedProfitLossOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLoss == nil {
		return nil, false
	}
	return o.UnrealizedProfitLoss, true
}

// HasUnrealizedProfitLoss returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasUnrealizedProfitLoss() bool {
	if o != nil && o.UnrealizedProfitLoss != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLoss gets a reference to the given string and assigns it to the UnrealizedProfitLoss field.
func (o *GetAccountsResponseV5Positions) SetUnrealizedProfitLoss(v string) {
	o.UnrealizedProfitLoss = &v
}

// GetUnrealizedProfitLossRate returns the UnrealizedProfitLossRate field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetUnrealizedProfitLossRate() string {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLossRate
}

// GetUnrealizedProfitLossRateOk returns a tuple with the UnrealizedProfitLossRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetUnrealizedProfitLossRateOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		return nil, false
	}
	return o.UnrealizedProfitLossRate, true
}

// HasUnrealizedProfitLossRate returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasUnrealizedProfitLossRate() bool {
	if o != nil && o.UnrealizedProfitLossRate != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLossRate gets a reference to the given string and assigns it to the UnrealizedProfitLossRate field.
func (o *GetAccountsResponseV5Positions) SetUnrealizedProfitLossRate(v string) {
	o.UnrealizedProfitLossRate = &v
}

// GetPositionProportion returns the PositionProportion field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetPositionProportion() string {
	if o == nil || o.PositionProportion == nil {
		var ret string
		return ret
	}
	return *o.PositionProportion
}

// GetPositionProportionOk returns a tuple with the PositionProportion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetPositionProportionOk() (*string, bool) {
	if o == nil || o.PositionProportion == nil {
		return nil, false
	}
	return o.PositionProportion, true
}

// HasPositionProportion returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasPositionProportion() bool {
	if o != nil && o.PositionProportion != nil {
		return true
	}

	return false
}

// SetPositionProportion gets a reference to the given string and assigns it to the PositionProportion field.
func (o *GetAccountsResponseV5Positions) SetPositionProportion(v string) {
	o.PositionProportion = &v
}

// GetUpdatePositionTime returns the UpdatePositionTime field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetUpdatePositionTime() float32 {
	if o == nil || o.UpdatePositionTime == nil {
		var ret float32
		return ret
	}
	return *o.UpdatePositionTime
}

// GetUpdatePositionTimeOk returns a tuple with the UpdatePositionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetUpdatePositionTimeOk() (*float32, bool) {
	if o == nil || o.UpdatePositionTime == nil {
		return nil, false
	}
	return o.UpdatePositionTime, true
}

// HasUpdatePositionTime returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasUpdatePositionTime() bool {
	if o != nil && o.UpdatePositionTime != nil {
		return true
	}

	return false
}

// SetUpdatePositionTime gets a reference to the given float32 and assigns it to the UpdatePositionTime field.
func (o *GetAccountsResponseV5Positions) SetUpdatePositionTime(v float32) {
	o.UpdatePositionTime = &v
}

// GetOptionCanExercise returns the OptionCanExercise field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetOptionCanExercise() float32 {
	if o == nil || o.OptionCanExercise == nil {
		var ret float32
		return ret
	}
	return *o.OptionCanExercise
}

// GetOptionCanExerciseOk returns a tuple with the OptionCanExercise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetOptionCanExerciseOk() (*float32, bool) {
	if o == nil || o.OptionCanExercise == nil {
		return nil, false
	}
	return o.OptionCanExercise, true
}

// HasOptionCanExercise returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasOptionCanExercise() bool {
	if o != nil && o.OptionCanExercise != nil {
		return true
	}

	return false
}

// SetOptionCanExercise gets a reference to the given float32 and assigns it to the OptionCanExercise field.
func (o *GetAccountsResponseV5Positions) SetOptionCanExercise(v float32) {
	o.OptionCanExercise = &v
}

// GetRecentlyExpireFlag returns the RecentlyExpireFlag field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetRecentlyExpireFlag() bool {
	if o == nil || o.RecentlyExpireFlag == nil {
		var ret bool
		return ret
	}
	return *o.RecentlyExpireFlag
}

// GetRecentlyExpireFlagOk returns a tuple with the RecentlyExpireFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetRecentlyExpireFlagOk() (*bool, bool) {
	if o == nil || o.RecentlyExpireFlag == nil {
		return nil, false
	}
	return o.RecentlyExpireFlag, true
}

// HasRecentlyExpireFlag returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasRecentlyExpireFlag() bool {
	if o != nil && o.RecentlyExpireFlag != nil {
		return true
	}

	return false
}

// SetRecentlyExpireFlag gets a reference to the given bool and assigns it to the RecentlyExpireFlag field.
func (o *GetAccountsResponseV5Positions) SetRecentlyExpireFlag(v bool) {
	o.RecentlyExpireFlag = &v
}

// GetRemainDay returns the RemainDay field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetRemainDay() float32 {
	if o == nil || o.RemainDay == nil {
		var ret float32
		return ret
	}
	return *o.RemainDay
}

// GetRemainDayOk returns a tuple with the RemainDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetRemainDayOk() (*float32, bool) {
	if o == nil || o.RemainDay == nil {
		return nil, false
	}
	return o.RemainDay, true
}

// HasRemainDay returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasRemainDay() bool {
	if o != nil && o.RemainDay != nil {
		return true
	}

	return false
}

// SetRemainDay gets a reference to the given float32 and assigns it to the RemainDay field.
func (o *GetAccountsResponseV5Positions) SetRemainDay(v float32) {
	o.RemainDay = &v
}

// GetIsLending returns the IsLending field value if set, zero value otherwise.
func (o *GetAccountsResponseV5Positions) GetIsLending() string {
	if o == nil || o.IsLending == nil {
		var ret string
		return ret
	}
	return *o.IsLending
}

// GetIsLendingOk returns a tuple with the IsLending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountsResponseV5Positions) GetIsLendingOk() (*string, bool) {
	if o == nil || o.IsLending == nil {
		return nil, false
	}
	return o.IsLending, true
}

// HasIsLending returns a boolean if a field has been set.
func (o *GetAccountsResponseV5Positions) HasIsLending() bool {
	if o != nil && o.IsLending != nil {
		return true
	}

	return false
}

// SetIsLending gets a reference to the given string and assigns it to the IsLending field.
func (o *GetAccountsResponseV5Positions) SetIsLending(v string) {
	o.IsLending = &v
}

func (o GetAccountsResponseV5Positions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PositionId != nil {
		toSerialize["positionId"] = o.PositionId
	}
	if o.BrokerPosId != nil {
		toSerialize["brokerPosId"] = o.BrokerPosId
	}
	if o.BrokerId != nil {
		toSerialize["brokerId"] = o.BrokerId
	}
	if o.AssetType != nil {
		toSerialize["assetType"] = o.AssetType
	}
	if o.TickerType != nil {
		toSerialize["tickerType"] = o.TickerType
	}
	if o.Ticker != nil {
		toSerialize["ticker"] = o.Ticker
	}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.TickerId != nil {
		toSerialize["tickerId"] = o.TickerId
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.CostPrice != nil {
		toSerialize["costPrice"] = o.CostPrice
	}
	if o.Cost != nil {
		toSerialize["cost"] = o.Cost
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.MarketValue != nil {
		toSerialize["marketValue"] = o.MarketValue
	}
	if o.LastPrice != nil {
		toSerialize["lastPrice"] = o.LastPrice
	}
	if o.UnrealizedProfitLoss != nil {
		toSerialize["unrealizedProfitLoss"] = o.UnrealizedProfitLoss
	}
	if o.UnrealizedProfitLossRate != nil {
		toSerialize["unrealizedProfitLossRate"] = o.UnrealizedProfitLossRate
	}
	if o.PositionProportion != nil {
		toSerialize["positionProportion"] = o.PositionProportion
	}
	if o.UpdatePositionTime != nil {
		toSerialize["updatePositionTime"] = o.UpdatePositionTime
	}
	if o.OptionCanExercise != nil {
		toSerialize["optionCanExercise"] = o.OptionCanExercise
	}
	if o.RecentlyExpireFlag != nil {
		toSerialize["recentlyExpireFlag"] = o.RecentlyExpireFlag
	}
	if o.RemainDay != nil {
		toSerialize["remainDay"] = o.RemainDay
	}
	if o.IsLending != nil {
		toSerialize["isLending"] = o.IsLending
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountsResponseV5Positions struct {
	value *GetAccountsResponseV5Positions
	isSet bool
}

func (v NullableGetAccountsResponseV5Positions) Get() *GetAccountsResponseV5Positions {
	return v.value
}

func (v *NullableGetAccountsResponseV5Positions) Set(val *GetAccountsResponseV5Positions) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountsResponseV5Positions) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountsResponseV5Positions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountsResponseV5Positions(val *GetAccountsResponseV5Positions) *NullableGetAccountsResponseV5Positions {
	return &NullableGetAccountsResponseV5Positions{value: val, isSet: true}
}

func (v NullableGetAccountsResponseV5Positions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountsResponseV5Positions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


