/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetUserDetailsResponse struct for GetUserDetailsResponse
type GetUserDetailsResponse struct {
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	Email *string `json:"email,omitempty"`
	NickName *string `json:"nickName,omitempty"`
	PwdFlag *int32 `json:"pwdFlag,omitempty"`
	RegionId *int32 `json:"regionId,omitempty"`
	RegionName *string `json:"regionName,omitempty"`
	Sex *int32 `json:"sex,omitempty"`
	ThirdAccounts *[]map[string]interface{} `json:"thirdAccounts,omitempty"`
	TradeLockemail *string `json:"tradeLockemail,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

// NewGetUserDetailsResponse instantiates a new GetUserDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserDetailsResponse() *GetUserDetailsResponse {
	this := GetUserDetailsResponse{}
	return &this
}

// NewGetUserDetailsResponseWithDefaults instantiates a new GetUserDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserDetailsResponseWithDefaults() *GetUserDetailsResponse {
	this := GetUserDetailsResponse{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetAvatarUrl() string {
	if o == nil || o.AvatarUrl == nil {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetAvatarUrlOk() (*string, bool) {
	if o == nil || o.AvatarUrl == nil {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasAvatarUrl() bool {
	if o != nil && o.AvatarUrl != nil {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *GetUserDetailsResponse) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetUserDetailsResponse) SetEmail(v string) {
	o.Email = &v
}

// GetNickName returns the NickName field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetNickName() string {
	if o == nil || o.NickName == nil {
		var ret string
		return ret
	}
	return *o.NickName
}

// GetNickNameOk returns a tuple with the NickName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetNickNameOk() (*string, bool) {
	if o == nil || o.NickName == nil {
		return nil, false
	}
	return o.NickName, true
}

// HasNickName returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasNickName() bool {
	if o != nil && o.NickName != nil {
		return true
	}

	return false
}

// SetNickName gets a reference to the given string and assigns it to the NickName field.
func (o *GetUserDetailsResponse) SetNickName(v string) {
	o.NickName = &v
}

// GetPwdFlag returns the PwdFlag field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetPwdFlag() int32 {
	if o == nil || o.PwdFlag == nil {
		var ret int32
		return ret
	}
	return *o.PwdFlag
}

// GetPwdFlagOk returns a tuple with the PwdFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetPwdFlagOk() (*int32, bool) {
	if o == nil || o.PwdFlag == nil {
		return nil, false
	}
	return o.PwdFlag, true
}

// HasPwdFlag returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasPwdFlag() bool {
	if o != nil && o.PwdFlag != nil {
		return true
	}

	return false
}

// SetPwdFlag gets a reference to the given int32 and assigns it to the PwdFlag field.
func (o *GetUserDetailsResponse) SetPwdFlag(v int32) {
	o.PwdFlag = &v
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetRegionId() int32 {
	if o == nil || o.RegionId == nil {
		var ret int32
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetRegionIdOk() (*int32, bool) {
	if o == nil || o.RegionId == nil {
		return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasRegionId() bool {
	if o != nil && o.RegionId != nil {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given int32 and assigns it to the RegionId field.
func (o *GetUserDetailsResponse) SetRegionId(v int32) {
	o.RegionId = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetRegionName() string {
	if o == nil || o.RegionName == nil {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetRegionNameOk() (*string, bool) {
	if o == nil || o.RegionName == nil {
		return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasRegionName() bool {
	if o != nil && o.RegionName != nil {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *GetUserDetailsResponse) SetRegionName(v string) {
	o.RegionName = &v
}

// GetSex returns the Sex field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetSex() int32 {
	if o == nil || o.Sex == nil {
		var ret int32
		return ret
	}
	return *o.Sex
}

// GetSexOk returns a tuple with the Sex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetSexOk() (*int32, bool) {
	if o == nil || o.Sex == nil {
		return nil, false
	}
	return o.Sex, true
}

// HasSex returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasSex() bool {
	if o != nil && o.Sex != nil {
		return true
	}

	return false
}

// SetSex gets a reference to the given int32 and assigns it to the Sex field.
func (o *GetUserDetailsResponse) SetSex(v int32) {
	o.Sex = &v
}

// GetThirdAccounts returns the ThirdAccounts field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetThirdAccounts() []map[string]interface{} {
	if o == nil || o.ThirdAccounts == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.ThirdAccounts
}

// GetThirdAccountsOk returns a tuple with the ThirdAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetThirdAccountsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.ThirdAccounts == nil {
		return nil, false
	}
	return o.ThirdAccounts, true
}

// HasThirdAccounts returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasThirdAccounts() bool {
	if o != nil && o.ThirdAccounts != nil {
		return true
	}

	return false
}

// SetThirdAccounts gets a reference to the given []map[string]interface{} and assigns it to the ThirdAccounts field.
func (o *GetUserDetailsResponse) SetThirdAccounts(v []map[string]interface{}) {
	o.ThirdAccounts = &v
}

// GetTradeLockemail returns the TradeLockemail field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetTradeLockemail() string {
	if o == nil || o.TradeLockemail == nil {
		var ret string
		return ret
	}
	return *o.TradeLockemail
}

// GetTradeLockemailOk returns a tuple with the TradeLockemail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetTradeLockemailOk() (*string, bool) {
	if o == nil || o.TradeLockemail == nil {
		return nil, false
	}
	return o.TradeLockemail, true
}

// HasTradeLockemail returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasTradeLockemail() bool {
	if o != nil && o.TradeLockemail != nil {
		return true
	}

	return false
}

// SetTradeLockemail gets a reference to the given string and assigns it to the TradeLockemail field.
func (o *GetUserDetailsResponse) SetTradeLockemail(v string) {
	o.TradeLockemail = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *GetUserDetailsResponse) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserDetailsResponse) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *GetUserDetailsResponse) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *GetUserDetailsResponse) SetUuid(v string) {
	o.Uuid = &v
}

func (o GetUserDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AvatarUrl != nil {
		toSerialize["avatarUrl"] = o.AvatarUrl
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.NickName != nil {
		toSerialize["nickName"] = o.NickName
	}
	if o.PwdFlag != nil {
		toSerialize["pwdFlag"] = o.PwdFlag
	}
	if o.RegionId != nil {
		toSerialize["regionId"] = o.RegionId
	}
	if o.RegionName != nil {
		toSerialize["regionName"] = o.RegionName
	}
	if o.Sex != nil {
		toSerialize["sex"] = o.Sex
	}
	if o.ThirdAccounts != nil {
		toSerialize["thirdAccounts"] = o.ThirdAccounts
	}
	if o.TradeLockemail != nil {
		toSerialize["tradeLockemail"] = o.TradeLockemail
	}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserDetailsResponse struct {
	value *GetUserDetailsResponse
	isSet bool
}

func (v NullableGetUserDetailsResponse) Get() *GetUserDetailsResponse {
	return v.value
}

func (v *NullableGetUserDetailsResponse) Set(val *GetUserDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserDetailsResponse(val *GetUserDetailsResponse) *NullableGetUserDetailsResponse {
	return &NullableGetUserDetailsResponse{value: val, isSet: true}
}

func (v NullableGetUserDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


