/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSecurityAccountsResponseData struct for GetSecurityAccountsResponseData
type GetSecurityAccountsResponseData struct {
	AccountTypes *[]string `json:"accountTypes,omitempty"`
	AllowDeposit *bool `json:"allowDeposit,omitempty"`
	BrokerAccountId *string `json:"brokerAccountId,omitempty"`
	BrokerId *int32 `json:"brokerId,omitempty"`
	BrokerName *string `json:"brokerName,omitempty"`
	ComboTypes *[]string `json:"comboTypes,omitempty"`
	CustomerType *string `json:"customerType,omitempty"`
	Deposit *bool `json:"deposit,omitempty"`
	DepositStatus *string `json:"depositStatus,omitempty"`
	GiftStockStatus *int32 `json:"giftStockStatus,omitempty"`
	IsDefault *bool `json:"isDefault,omitempty"`
	IsDefaultChecked *bool `json:"isDefaultChecked,omitempty"`
	OpenAccountUrl *string `json:"openAccountUrl,omitempty"`
	OptionOpenStatus *string `json:"optionOpenStatus,omitempty"`
	RegisterRegionId *int32 `json:"registerRegionId,omitempty"`
	RegisterTradeUrl *string `json:"registerTradeUrl,omitempty"`
	SecAccountId *int32 `json:"secAccountId,omitempty"`
	Status *string `json:"status,omitempty"`
	SupportClickIPO *bool `json:"supportClickIPO,omitempty"`
	SupportOpenOption *bool `json:"supportOpenOption,omitempty"`
	SupportOutsideRth *bool `json:"supportOutsideRth,omitempty"`
	TickerTypes *[]GetSecurityAccountsResponseTickerTypes `json:"tickerTypes,omitempty"`
	TimeInForces *[]GetSecurityAccountsResponseTimeInForces `json:"timeInForces,omitempty"`
	UserTradePermissionVOs *[]GetSecurityAccountsResponseUserTradePermissionVOs `json:"userTradePermissionVOs,omitempty"`
}

// NewGetSecurityAccountsResponseData instantiates a new GetSecurityAccountsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecurityAccountsResponseData() *GetSecurityAccountsResponseData {
	this := GetSecurityAccountsResponseData{}
	return &this
}

// NewGetSecurityAccountsResponseDataWithDefaults instantiates a new GetSecurityAccountsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecurityAccountsResponseDataWithDefaults() *GetSecurityAccountsResponseData {
	this := GetSecurityAccountsResponseData{}
	return &this
}

// GetAccountTypes returns the AccountTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetAccountTypes() []string {
	if o == nil || o.AccountTypes == nil {
		var ret []string
		return ret
	}
	return *o.AccountTypes
}

// GetAccountTypesOk returns a tuple with the AccountTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetAccountTypesOk() (*[]string, bool) {
	if o == nil || o.AccountTypes == nil {
		return nil, false
	}
	return o.AccountTypes, true
}

// HasAccountTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasAccountTypes() bool {
	if o != nil && o.AccountTypes != nil {
		return true
	}

	return false
}

// SetAccountTypes gets a reference to the given []string and assigns it to the AccountTypes field.
func (o *GetSecurityAccountsResponseData) SetAccountTypes(v []string) {
	o.AccountTypes = &v
}

// GetAllowDeposit returns the AllowDeposit field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetAllowDeposit() bool {
	if o == nil || o.AllowDeposit == nil {
		var ret bool
		return ret
	}
	return *o.AllowDeposit
}

// GetAllowDepositOk returns a tuple with the AllowDeposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetAllowDepositOk() (*bool, bool) {
	if o == nil || o.AllowDeposit == nil {
		return nil, false
	}
	return o.AllowDeposit, true
}

// HasAllowDeposit returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasAllowDeposit() bool {
	if o != nil && o.AllowDeposit != nil {
		return true
	}

	return false
}

// SetAllowDeposit gets a reference to the given bool and assigns it to the AllowDeposit field.
func (o *GetSecurityAccountsResponseData) SetAllowDeposit(v bool) {
	o.AllowDeposit = &v
}

// GetBrokerAccountId returns the BrokerAccountId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetBrokerAccountId() string {
	if o == nil || o.BrokerAccountId == nil {
		var ret string
		return ret
	}
	return *o.BrokerAccountId
}

// GetBrokerAccountIdOk returns a tuple with the BrokerAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetBrokerAccountIdOk() (*string, bool) {
	if o == nil || o.BrokerAccountId == nil {
		return nil, false
	}
	return o.BrokerAccountId, true
}

// HasBrokerAccountId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasBrokerAccountId() bool {
	if o != nil && o.BrokerAccountId != nil {
		return true
	}

	return false
}

// SetBrokerAccountId gets a reference to the given string and assigns it to the BrokerAccountId field.
func (o *GetSecurityAccountsResponseData) SetBrokerAccountId(v string) {
	o.BrokerAccountId = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetBrokerId() int32 {
	if o == nil || o.BrokerId == nil {
		var ret int32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetBrokerIdOk() (*int32, bool) {
	if o == nil || o.BrokerId == nil {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasBrokerId() bool {
	if o != nil && o.BrokerId != nil {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given int32 and assigns it to the BrokerId field.
func (o *GetSecurityAccountsResponseData) SetBrokerId(v int32) {
	o.BrokerId = &v
}

// GetBrokerName returns the BrokerName field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetBrokerName() string {
	if o == nil || o.BrokerName == nil {
		var ret string
		return ret
	}
	return *o.BrokerName
}

// GetBrokerNameOk returns a tuple with the BrokerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetBrokerNameOk() (*string, bool) {
	if o == nil || o.BrokerName == nil {
		return nil, false
	}
	return o.BrokerName, true
}

// HasBrokerName returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasBrokerName() bool {
	if o != nil && o.BrokerName != nil {
		return true
	}

	return false
}

// SetBrokerName gets a reference to the given string and assigns it to the BrokerName field.
func (o *GetSecurityAccountsResponseData) SetBrokerName(v string) {
	o.BrokerName = &v
}

// GetComboTypes returns the ComboTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetComboTypes() []string {
	if o == nil || o.ComboTypes == nil {
		var ret []string
		return ret
	}
	return *o.ComboTypes
}

// GetComboTypesOk returns a tuple with the ComboTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetComboTypesOk() (*[]string, bool) {
	if o == nil || o.ComboTypes == nil {
		return nil, false
	}
	return o.ComboTypes, true
}

// HasComboTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasComboTypes() bool {
	if o != nil && o.ComboTypes != nil {
		return true
	}

	return false
}

// SetComboTypes gets a reference to the given []string and assigns it to the ComboTypes field.
func (o *GetSecurityAccountsResponseData) SetComboTypes(v []string) {
	o.ComboTypes = &v
}

// GetCustomerType returns the CustomerType field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetCustomerType() string {
	if o == nil || o.CustomerType == nil {
		var ret string
		return ret
	}
	return *o.CustomerType
}

// GetCustomerTypeOk returns a tuple with the CustomerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetCustomerTypeOk() (*string, bool) {
	if o == nil || o.CustomerType == nil {
		return nil, false
	}
	return o.CustomerType, true
}

// HasCustomerType returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasCustomerType() bool {
	if o != nil && o.CustomerType != nil {
		return true
	}

	return false
}

// SetCustomerType gets a reference to the given string and assigns it to the CustomerType field.
func (o *GetSecurityAccountsResponseData) SetCustomerType(v string) {
	o.CustomerType = &v
}

// GetDeposit returns the Deposit field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetDeposit() bool {
	if o == nil || o.Deposit == nil {
		var ret bool
		return ret
	}
	return *o.Deposit
}

// GetDepositOk returns a tuple with the Deposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetDepositOk() (*bool, bool) {
	if o == nil || o.Deposit == nil {
		return nil, false
	}
	return o.Deposit, true
}

// HasDeposit returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasDeposit() bool {
	if o != nil && o.Deposit != nil {
		return true
	}

	return false
}

// SetDeposit gets a reference to the given bool and assigns it to the Deposit field.
func (o *GetSecurityAccountsResponseData) SetDeposit(v bool) {
	o.Deposit = &v
}

// GetDepositStatus returns the DepositStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetDepositStatus() string {
	if o == nil || o.DepositStatus == nil {
		var ret string
		return ret
	}
	return *o.DepositStatus
}

// GetDepositStatusOk returns a tuple with the DepositStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetDepositStatusOk() (*string, bool) {
	if o == nil || o.DepositStatus == nil {
		return nil, false
	}
	return o.DepositStatus, true
}

// HasDepositStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasDepositStatus() bool {
	if o != nil && o.DepositStatus != nil {
		return true
	}

	return false
}

// SetDepositStatus gets a reference to the given string and assigns it to the DepositStatus field.
func (o *GetSecurityAccountsResponseData) SetDepositStatus(v string) {
	o.DepositStatus = &v
}

// GetGiftStockStatus returns the GiftStockStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetGiftStockStatus() int32 {
	if o == nil || o.GiftStockStatus == nil {
		var ret int32
		return ret
	}
	return *o.GiftStockStatus
}

// GetGiftStockStatusOk returns a tuple with the GiftStockStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetGiftStockStatusOk() (*int32, bool) {
	if o == nil || o.GiftStockStatus == nil {
		return nil, false
	}
	return o.GiftStockStatus, true
}

// HasGiftStockStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasGiftStockStatus() bool {
	if o != nil && o.GiftStockStatus != nil {
		return true
	}

	return false
}

// SetGiftStockStatus gets a reference to the given int32 and assigns it to the GiftStockStatus field.
func (o *GetSecurityAccountsResponseData) SetGiftStockStatus(v int32) {
	o.GiftStockStatus = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetIsDefault() bool {
	if o == nil || o.IsDefault == nil {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetIsDefaultOk() (*bool, bool) {
	if o == nil || o.IsDefault == nil {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasIsDefault() bool {
	if o != nil && o.IsDefault != nil {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *GetSecurityAccountsResponseData) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetIsDefaultChecked returns the IsDefaultChecked field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetIsDefaultChecked() bool {
	if o == nil || o.IsDefaultChecked == nil {
		var ret bool
		return ret
	}
	return *o.IsDefaultChecked
}

// GetIsDefaultCheckedOk returns a tuple with the IsDefaultChecked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetIsDefaultCheckedOk() (*bool, bool) {
	if o == nil || o.IsDefaultChecked == nil {
		return nil, false
	}
	return o.IsDefaultChecked, true
}

// HasIsDefaultChecked returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasIsDefaultChecked() bool {
	if o != nil && o.IsDefaultChecked != nil {
		return true
	}

	return false
}

// SetIsDefaultChecked gets a reference to the given bool and assigns it to the IsDefaultChecked field.
func (o *GetSecurityAccountsResponseData) SetIsDefaultChecked(v bool) {
	o.IsDefaultChecked = &v
}

// GetOpenAccountUrl returns the OpenAccountUrl field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetOpenAccountUrl() string {
	if o == nil || o.OpenAccountUrl == nil {
		var ret string
		return ret
	}
	return *o.OpenAccountUrl
}

// GetOpenAccountUrlOk returns a tuple with the OpenAccountUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetOpenAccountUrlOk() (*string, bool) {
	if o == nil || o.OpenAccountUrl == nil {
		return nil, false
	}
	return o.OpenAccountUrl, true
}

// HasOpenAccountUrl returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasOpenAccountUrl() bool {
	if o != nil && o.OpenAccountUrl != nil {
		return true
	}

	return false
}

// SetOpenAccountUrl gets a reference to the given string and assigns it to the OpenAccountUrl field.
func (o *GetSecurityAccountsResponseData) SetOpenAccountUrl(v string) {
	o.OpenAccountUrl = &v
}

// GetOptionOpenStatus returns the OptionOpenStatus field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetOptionOpenStatus() string {
	if o == nil || o.OptionOpenStatus == nil {
		var ret string
		return ret
	}
	return *o.OptionOpenStatus
}

// GetOptionOpenStatusOk returns a tuple with the OptionOpenStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetOptionOpenStatusOk() (*string, bool) {
	if o == nil || o.OptionOpenStatus == nil {
		return nil, false
	}
	return o.OptionOpenStatus, true
}

// HasOptionOpenStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasOptionOpenStatus() bool {
	if o != nil && o.OptionOpenStatus != nil {
		return true
	}

	return false
}

// SetOptionOpenStatus gets a reference to the given string and assigns it to the OptionOpenStatus field.
func (o *GetSecurityAccountsResponseData) SetOptionOpenStatus(v string) {
	o.OptionOpenStatus = &v
}

// GetRegisterRegionId returns the RegisterRegionId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetRegisterRegionId() int32 {
	if o == nil || o.RegisterRegionId == nil {
		var ret int32
		return ret
	}
	return *o.RegisterRegionId
}

// GetRegisterRegionIdOk returns a tuple with the RegisterRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetRegisterRegionIdOk() (*int32, bool) {
	if o == nil || o.RegisterRegionId == nil {
		return nil, false
	}
	return o.RegisterRegionId, true
}

// HasRegisterRegionId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasRegisterRegionId() bool {
	if o != nil && o.RegisterRegionId != nil {
		return true
	}

	return false
}

// SetRegisterRegionId gets a reference to the given int32 and assigns it to the RegisterRegionId field.
func (o *GetSecurityAccountsResponseData) SetRegisterRegionId(v int32) {
	o.RegisterRegionId = &v
}

// GetRegisterTradeUrl returns the RegisterTradeUrl field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetRegisterTradeUrl() string {
	if o == nil || o.RegisterTradeUrl == nil {
		var ret string
		return ret
	}
	return *o.RegisterTradeUrl
}

// GetRegisterTradeUrlOk returns a tuple with the RegisterTradeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetRegisterTradeUrlOk() (*string, bool) {
	if o == nil || o.RegisterTradeUrl == nil {
		return nil, false
	}
	return o.RegisterTradeUrl, true
}

// HasRegisterTradeUrl returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasRegisterTradeUrl() bool {
	if o != nil && o.RegisterTradeUrl != nil {
		return true
	}

	return false
}

// SetRegisterTradeUrl gets a reference to the given string and assigns it to the RegisterTradeUrl field.
func (o *GetSecurityAccountsResponseData) SetRegisterTradeUrl(v string) {
	o.RegisterTradeUrl = &v
}

// GetSecAccountId returns the SecAccountId field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetSecAccountId() int32 {
	if o == nil || o.SecAccountId == nil {
		var ret int32
		return ret
	}
	return *o.SecAccountId
}

// GetSecAccountIdOk returns a tuple with the SecAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetSecAccountIdOk() (*int32, bool) {
	if o == nil || o.SecAccountId == nil {
		return nil, false
	}
	return o.SecAccountId, true
}

// HasSecAccountId returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasSecAccountId() bool {
	if o != nil && o.SecAccountId != nil {
		return true
	}

	return false
}

// SetSecAccountId gets a reference to the given int32 and assigns it to the SecAccountId field.
func (o *GetSecurityAccountsResponseData) SetSecAccountId(v int32) {
	o.SecAccountId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetSecurityAccountsResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetSupportClickIPO returns the SupportClickIPO field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetSupportClickIPO() bool {
	if o == nil || o.SupportClickIPO == nil {
		var ret bool
		return ret
	}
	return *o.SupportClickIPO
}

// GetSupportClickIPOOk returns a tuple with the SupportClickIPO field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetSupportClickIPOOk() (*bool, bool) {
	if o == nil || o.SupportClickIPO == nil {
		return nil, false
	}
	return o.SupportClickIPO, true
}

// HasSupportClickIPO returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasSupportClickIPO() bool {
	if o != nil && o.SupportClickIPO != nil {
		return true
	}

	return false
}

// SetSupportClickIPO gets a reference to the given bool and assigns it to the SupportClickIPO field.
func (o *GetSecurityAccountsResponseData) SetSupportClickIPO(v bool) {
	o.SupportClickIPO = &v
}

// GetSupportOpenOption returns the SupportOpenOption field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetSupportOpenOption() bool {
	if o == nil || o.SupportOpenOption == nil {
		var ret bool
		return ret
	}
	return *o.SupportOpenOption
}

// GetSupportOpenOptionOk returns a tuple with the SupportOpenOption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetSupportOpenOptionOk() (*bool, bool) {
	if o == nil || o.SupportOpenOption == nil {
		return nil, false
	}
	return o.SupportOpenOption, true
}

// HasSupportOpenOption returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasSupportOpenOption() bool {
	if o != nil && o.SupportOpenOption != nil {
		return true
	}

	return false
}

// SetSupportOpenOption gets a reference to the given bool and assigns it to the SupportOpenOption field.
func (o *GetSecurityAccountsResponseData) SetSupportOpenOption(v bool) {
	o.SupportOpenOption = &v
}

// GetSupportOutsideRth returns the SupportOutsideRth field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetSupportOutsideRth() bool {
	if o == nil || o.SupportOutsideRth == nil {
		var ret bool
		return ret
	}
	return *o.SupportOutsideRth
}

// GetSupportOutsideRthOk returns a tuple with the SupportOutsideRth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetSupportOutsideRthOk() (*bool, bool) {
	if o == nil || o.SupportOutsideRth == nil {
		return nil, false
	}
	return o.SupportOutsideRth, true
}

// HasSupportOutsideRth returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasSupportOutsideRth() bool {
	if o != nil && o.SupportOutsideRth != nil {
		return true
	}

	return false
}

// SetSupportOutsideRth gets a reference to the given bool and assigns it to the SupportOutsideRth field.
func (o *GetSecurityAccountsResponseData) SetSupportOutsideRth(v bool) {
	o.SupportOutsideRth = &v
}

// GetTickerTypes returns the TickerTypes field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetTickerTypes() []GetSecurityAccountsResponseTickerTypes {
	if o == nil || o.TickerTypes == nil {
		var ret []GetSecurityAccountsResponseTickerTypes
		return ret
	}
	return *o.TickerTypes
}

// GetTickerTypesOk returns a tuple with the TickerTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetTickerTypesOk() (*[]GetSecurityAccountsResponseTickerTypes, bool) {
	if o == nil || o.TickerTypes == nil {
		return nil, false
	}
	return o.TickerTypes, true
}

// HasTickerTypes returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasTickerTypes() bool {
	if o != nil && o.TickerTypes != nil {
		return true
	}

	return false
}

// SetTickerTypes gets a reference to the given []GetSecurityAccountsResponseTickerTypes and assigns it to the TickerTypes field.
func (o *GetSecurityAccountsResponseData) SetTickerTypes(v []GetSecurityAccountsResponseTickerTypes) {
	o.TickerTypes = &v
}

// GetTimeInForces returns the TimeInForces field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetTimeInForces() []GetSecurityAccountsResponseTimeInForces {
	if o == nil || o.TimeInForces == nil {
		var ret []GetSecurityAccountsResponseTimeInForces
		return ret
	}
	return *o.TimeInForces
}

// GetTimeInForcesOk returns a tuple with the TimeInForces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetTimeInForcesOk() (*[]GetSecurityAccountsResponseTimeInForces, bool) {
	if o == nil || o.TimeInForces == nil {
		return nil, false
	}
	return o.TimeInForces, true
}

// HasTimeInForces returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasTimeInForces() bool {
	if o != nil && o.TimeInForces != nil {
		return true
	}

	return false
}

// SetTimeInForces gets a reference to the given []GetSecurityAccountsResponseTimeInForces and assigns it to the TimeInForces field.
func (o *GetSecurityAccountsResponseData) SetTimeInForces(v []GetSecurityAccountsResponseTimeInForces) {
	o.TimeInForces = &v
}

// GetUserTradePermissionVOs returns the UserTradePermissionVOs field value if set, zero value otherwise.
func (o *GetSecurityAccountsResponseData) GetUserTradePermissionVOs() []GetSecurityAccountsResponseUserTradePermissionVOs {
	if o == nil || o.UserTradePermissionVOs == nil {
		var ret []GetSecurityAccountsResponseUserTradePermissionVOs
		return ret
	}
	return *o.UserTradePermissionVOs
}

// GetUserTradePermissionVOsOk returns a tuple with the UserTradePermissionVOs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecurityAccountsResponseData) GetUserTradePermissionVOsOk() (*[]GetSecurityAccountsResponseUserTradePermissionVOs, bool) {
	if o == nil || o.UserTradePermissionVOs == nil {
		return nil, false
	}
	return o.UserTradePermissionVOs, true
}

// HasUserTradePermissionVOs returns a boolean if a field has been set.
func (o *GetSecurityAccountsResponseData) HasUserTradePermissionVOs() bool {
	if o != nil && o.UserTradePermissionVOs != nil {
		return true
	}

	return false
}

// SetUserTradePermissionVOs gets a reference to the given []GetSecurityAccountsResponseUserTradePermissionVOs and assigns it to the UserTradePermissionVOs field.
func (o *GetSecurityAccountsResponseData) SetUserTradePermissionVOs(v []GetSecurityAccountsResponseUserTradePermissionVOs) {
	o.UserTradePermissionVOs = &v
}

func (o GetSecurityAccountsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountTypes != nil {
		toSerialize["accountTypes"] = o.AccountTypes
	}
	if o.AllowDeposit != nil {
		toSerialize["allowDeposit"] = o.AllowDeposit
	}
	if o.BrokerAccountId != nil {
		toSerialize["brokerAccountId"] = o.BrokerAccountId
	}
	if o.BrokerId != nil {
		toSerialize["brokerId"] = o.BrokerId
	}
	if o.BrokerName != nil {
		toSerialize["brokerName"] = o.BrokerName
	}
	if o.ComboTypes != nil {
		toSerialize["comboTypes"] = o.ComboTypes
	}
	if o.CustomerType != nil {
		toSerialize["customerType"] = o.CustomerType
	}
	if o.Deposit != nil {
		toSerialize["deposit"] = o.Deposit
	}
	if o.DepositStatus != nil {
		toSerialize["depositStatus"] = o.DepositStatus
	}
	if o.GiftStockStatus != nil {
		toSerialize["giftStockStatus"] = o.GiftStockStatus
	}
	if o.IsDefault != nil {
		toSerialize["isDefault"] = o.IsDefault
	}
	if o.IsDefaultChecked != nil {
		toSerialize["isDefaultChecked"] = o.IsDefaultChecked
	}
	if o.OpenAccountUrl != nil {
		toSerialize["openAccountUrl"] = o.OpenAccountUrl
	}
	if o.OptionOpenStatus != nil {
		toSerialize["optionOpenStatus"] = o.OptionOpenStatus
	}
	if o.RegisterRegionId != nil {
		toSerialize["registerRegionId"] = o.RegisterRegionId
	}
	if o.RegisterTradeUrl != nil {
		toSerialize["registerTradeUrl"] = o.RegisterTradeUrl
	}
	if o.SecAccountId != nil {
		toSerialize["secAccountId"] = o.SecAccountId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.SupportClickIPO != nil {
		toSerialize["supportClickIPO"] = o.SupportClickIPO
	}
	if o.SupportOpenOption != nil {
		toSerialize["supportOpenOption"] = o.SupportOpenOption
	}
	if o.SupportOutsideRth != nil {
		toSerialize["supportOutsideRth"] = o.SupportOutsideRth
	}
	if o.TickerTypes != nil {
		toSerialize["tickerTypes"] = o.TickerTypes
	}
	if o.TimeInForces != nil {
		toSerialize["timeInForces"] = o.TimeInForces
	}
	if o.UserTradePermissionVOs != nil {
		toSerialize["userTradePermissionVOs"] = o.UserTradePermissionVOs
	}
	return json.Marshal(toSerialize)
}

type NullableGetSecurityAccountsResponseData struct {
	value *GetSecurityAccountsResponseData
	isSet bool
}

func (v NullableGetSecurityAccountsResponseData) Get() *GetSecurityAccountsResponseData {
	return v.value
}

func (v *NullableGetSecurityAccountsResponseData) Set(val *GetSecurityAccountsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecurityAccountsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecurityAccountsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecurityAccountsResponseData(val *GetSecurityAccountsResponseData) *NullableGetSecurityAccountsResponseData {
	return &NullableGetSecurityAccountsResponseData{value: val, isSet: true}
}

func (v NullableGetSecurityAccountsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecurityAccountsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


