/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostLoginResponseSettings struct for PostLoginResponseSettings
type PostLoginResponseSettings struct {
	Id float32 `json:"id,omitempty"`
	UserId float32 `json:"userId,omitempty"`
	RegionId float32 `json:"regionId,omitempty"`
	Language string `json:"language,omitempty"`
	FocusMarketId string `json:"focusMarketId,omitempty"`
	Theme float32 `json:"theme,omitempty"`
	IncreDecreColor float32 `json:"increDecreColor,omitempty"`
	FontSize string `json:"fontSize,omitempty"`
	PortfolioDisplayMode float32 `json:"portfolioDisplayMode,omitempty"`
	PortfolioNameNewline float32 `json:"portfolioNameNewline,omitempty"`
	PortfolioHoldingsDisplay float32 `json:"portfolioHoldingsDisplay,omitempty"`
	PortfolioIndexDisplay float32 `json:"portfolioIndexDisplay,omitempty"`
	PortfolioBulletin float32 `json:"portfolioBulletin,omitempty"`
	Kdata float32 `json:"kdata,omitempty"`
	RefreshFrequency float32 `json:"refreshFrequency,omitempty"`
	Shock float32 `json:"shock,omitempty"`
	TickerPriceRemind float32 `json:"tickerPriceRemind,omitempty"`
	OrderDealRemind float32 `json:"orderDealRemind,omitempty"`
	HotNews float32 `json:"hotNews,omitempty"`
	ChartOption float32 `json:"chartOption,omitempty"`
	OperateTime string `json:"operateTime,omitempty"`
	LanguageUpdateTime string `json:"languageUpdateTime,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	UpdateTime string `json:"updateTime,omitempty"`
	ListStyle float32 `json:"listStyle,omitempty"`
}
