/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetStockAnalysisResponseRatingRatingSpread struct for GetStockAnalysisResponseRatingRatingSpread
type GetStockAnalysisResponseRatingRatingSpread struct {
	Buy float32 `json:"buy,omitempty"`
	Hold float32 `json:"hold,omitempty"`
	Sell float32 `json:"sell,omitempty"`
	StrongBuy float32 `json:"strongBuy,omitempty"`
	UnderPerform float32 `json:"underPerform,omitempty"`
}
