/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAcccountRequestPositions struct for GetAcccountRequestPositions
type GetAcccountRequestPositions struct {
	AssetType *string `json:"assetType,omitempty"`
	BrokerId *int32 `json:"brokerId,omitempty"`
	Cost *string `json:"cost,omitempty"`
	CostPrice *string `json:"costPrice,omitempty"`
	Currency *string `json:"currency,omitempty"`
	ExchangeRate *string `json:"exchangeRate,omitempty"`
	Id *int32 `json:"id,omitempty"`
	LastOpenTime *string `json:"lastOpenTime,omitempty"`
	LastPrice *string `json:"lastPrice,omitempty"`
	Lock *bool `json:"lock,omitempty"`
	MarketValue *string `json:"marketValue,omitempty"`
	Position *string `json:"position,omitempty"`
	PositionProportion *string `json:"positionProportion,omitempty"`
	Ticker *GetAcccountRequestTicker `json:"ticker,omitempty"`
	UnrealizedProfitLoss *string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossRate *string `json:"unrealizedProfitLossRate,omitempty"`
	UpdatePositionTimeStamp *float32 `json:"updatePositionTimeStamp,omitempty"`
}

// NewGetAcccountRequestPositions instantiates a new GetAcccountRequestPositions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAcccountRequestPositions() *GetAcccountRequestPositions {
	this := GetAcccountRequestPositions{}
	return &this
}

// NewGetAcccountRequestPositionsWithDefaults instantiates a new GetAcccountRequestPositions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAcccountRequestPositionsWithDefaults() *GetAcccountRequestPositions {
	this := GetAcccountRequestPositions{}
	return &this
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetAssetType() string {
	if o == nil || o.AssetType == nil {
		var ret string
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetAssetTypeOk() (*string, bool) {
	if o == nil || o.AssetType == nil {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasAssetType() bool {
	if o != nil && o.AssetType != nil {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given string and assigns it to the AssetType field.
func (o *GetAcccountRequestPositions) SetAssetType(v string) {
	o.AssetType = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetBrokerId() int32 {
	if o == nil || o.BrokerId == nil {
		var ret int32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetBrokerIdOk() (*int32, bool) {
	if o == nil || o.BrokerId == nil {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasBrokerId() bool {
	if o != nil && o.BrokerId != nil {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given int32 and assigns it to the BrokerId field.
func (o *GetAcccountRequestPositions) SetBrokerId(v int32) {
	o.BrokerId = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetCost() string {
	if o == nil || o.Cost == nil {
		var ret string
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetCostOk() (*string, bool) {
	if o == nil || o.Cost == nil {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasCost() bool {
	if o != nil && o.Cost != nil {
		return true
	}

	return false
}

// SetCost gets a reference to the given string and assigns it to the Cost field.
func (o *GetAcccountRequestPositions) SetCost(v string) {
	o.Cost = &v
}

// GetCostPrice returns the CostPrice field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetCostPrice() string {
	if o == nil || o.CostPrice == nil {
		var ret string
		return ret
	}
	return *o.CostPrice
}

// GetCostPriceOk returns a tuple with the CostPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetCostPriceOk() (*string, bool) {
	if o == nil || o.CostPrice == nil {
		return nil, false
	}
	return o.CostPrice, true
}

// HasCostPrice returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasCostPrice() bool {
	if o != nil && o.CostPrice != nil {
		return true
	}

	return false
}

// SetCostPrice gets a reference to the given string and assigns it to the CostPrice field.
func (o *GetAcccountRequestPositions) SetCostPrice(v string) {
	o.CostPrice = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetAcccountRequestPositions) SetCurrency(v string) {
	o.Currency = &v
}

// GetExchangeRate returns the ExchangeRate field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetExchangeRate() string {
	if o == nil || o.ExchangeRate == nil {
		var ret string
		return ret
	}
	return *o.ExchangeRate
}

// GetExchangeRateOk returns a tuple with the ExchangeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetExchangeRateOk() (*string, bool) {
	if o == nil || o.ExchangeRate == nil {
		return nil, false
	}
	return o.ExchangeRate, true
}

// HasExchangeRate returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasExchangeRate() bool {
	if o != nil && o.ExchangeRate != nil {
		return true
	}

	return false
}

// SetExchangeRate gets a reference to the given string and assigns it to the ExchangeRate field.
func (o *GetAcccountRequestPositions) SetExchangeRate(v string) {
	o.ExchangeRate = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetAcccountRequestPositions) SetId(v int32) {
	o.Id = &v
}

// GetLastOpenTime returns the LastOpenTime field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetLastOpenTime() string {
	if o == nil || o.LastOpenTime == nil {
		var ret string
		return ret
	}
	return *o.LastOpenTime
}

// GetLastOpenTimeOk returns a tuple with the LastOpenTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetLastOpenTimeOk() (*string, bool) {
	if o == nil || o.LastOpenTime == nil {
		return nil, false
	}
	return o.LastOpenTime, true
}

// HasLastOpenTime returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasLastOpenTime() bool {
	if o != nil && o.LastOpenTime != nil {
		return true
	}

	return false
}

// SetLastOpenTime gets a reference to the given string and assigns it to the LastOpenTime field.
func (o *GetAcccountRequestPositions) SetLastOpenTime(v string) {
	o.LastOpenTime = &v
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetLastPrice() string {
	if o == nil || o.LastPrice == nil {
		var ret string
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetLastPriceOk() (*string, bool) {
	if o == nil || o.LastPrice == nil {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasLastPrice() bool {
	if o != nil && o.LastPrice != nil {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given string and assigns it to the LastPrice field.
func (o *GetAcccountRequestPositions) SetLastPrice(v string) {
	o.LastPrice = &v
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetLock() bool {
	if o == nil || o.Lock == nil {
		var ret bool
		return ret
	}
	return *o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetLockOk() (*bool, bool) {
	if o == nil || o.Lock == nil {
		return nil, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasLock() bool {
	if o != nil && o.Lock != nil {
		return true
	}

	return false
}

// SetLock gets a reference to the given bool and assigns it to the Lock field.
func (o *GetAcccountRequestPositions) SetLock(v bool) {
	o.Lock = &v
}

// GetMarketValue returns the MarketValue field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetMarketValue() string {
	if o == nil || o.MarketValue == nil {
		var ret string
		return ret
	}
	return *o.MarketValue
}

// GetMarketValueOk returns a tuple with the MarketValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetMarketValueOk() (*string, bool) {
	if o == nil || o.MarketValue == nil {
		return nil, false
	}
	return o.MarketValue, true
}

// HasMarketValue returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasMarketValue() bool {
	if o != nil && o.MarketValue != nil {
		return true
	}

	return false
}

// SetMarketValue gets a reference to the given string and assigns it to the MarketValue field.
func (o *GetAcccountRequestPositions) SetMarketValue(v string) {
	o.MarketValue = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetPosition() string {
	if o == nil || o.Position == nil {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetPositionOk() (*string, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *GetAcccountRequestPositions) SetPosition(v string) {
	o.Position = &v
}

// GetPositionProportion returns the PositionProportion field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetPositionProportion() string {
	if o == nil || o.PositionProportion == nil {
		var ret string
		return ret
	}
	return *o.PositionProportion
}

// GetPositionProportionOk returns a tuple with the PositionProportion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetPositionProportionOk() (*string, bool) {
	if o == nil || o.PositionProportion == nil {
		return nil, false
	}
	return o.PositionProportion, true
}

// HasPositionProportion returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasPositionProportion() bool {
	if o != nil && o.PositionProportion != nil {
		return true
	}

	return false
}

// SetPositionProportion gets a reference to the given string and assigns it to the PositionProportion field.
func (o *GetAcccountRequestPositions) SetPositionProportion(v string) {
	o.PositionProportion = &v
}

// GetTicker returns the Ticker field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetTicker() GetAcccountRequestTicker {
	if o == nil || o.Ticker == nil {
		var ret GetAcccountRequestTicker
		return ret
	}
	return *o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetTickerOk() (*GetAcccountRequestTicker, bool) {
	if o == nil || o.Ticker == nil {
		return nil, false
	}
	return o.Ticker, true
}

// HasTicker returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasTicker() bool {
	if o != nil && o.Ticker != nil {
		return true
	}

	return false
}

// SetTicker gets a reference to the given GetAcccountRequestTicker and assigns it to the Ticker field.
func (o *GetAcccountRequestPositions) SetTicker(v GetAcccountRequestTicker) {
	o.Ticker = &v
}

// GetUnrealizedProfitLoss returns the UnrealizedProfitLoss field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetUnrealizedProfitLoss() string {
	if o == nil || o.UnrealizedProfitLoss == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLoss
}

// GetUnrealizedProfitLossOk returns a tuple with the UnrealizedProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetUnrealizedProfitLossOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLoss == nil {
		return nil, false
	}
	return o.UnrealizedProfitLoss, true
}

// HasUnrealizedProfitLoss returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasUnrealizedProfitLoss() bool {
	if o != nil && o.UnrealizedProfitLoss != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLoss gets a reference to the given string and assigns it to the UnrealizedProfitLoss field.
func (o *GetAcccountRequestPositions) SetUnrealizedProfitLoss(v string) {
	o.UnrealizedProfitLoss = &v
}

// GetUnrealizedProfitLossRate returns the UnrealizedProfitLossRate field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetUnrealizedProfitLossRate() string {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLossRate
}

// GetUnrealizedProfitLossRateOk returns a tuple with the UnrealizedProfitLossRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetUnrealizedProfitLossRateOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		return nil, false
	}
	return o.UnrealizedProfitLossRate, true
}

// HasUnrealizedProfitLossRate returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasUnrealizedProfitLossRate() bool {
	if o != nil && o.UnrealizedProfitLossRate != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLossRate gets a reference to the given string and assigns it to the UnrealizedProfitLossRate field.
func (o *GetAcccountRequestPositions) SetUnrealizedProfitLossRate(v string) {
	o.UnrealizedProfitLossRate = &v
}

// GetUpdatePositionTimeStamp returns the UpdatePositionTimeStamp field value if set, zero value otherwise.
func (o *GetAcccountRequestPositions) GetUpdatePositionTimeStamp() float32 {
	if o == nil || o.UpdatePositionTimeStamp == nil {
		var ret float32
		return ret
	}
	return *o.UpdatePositionTimeStamp
}

// GetUpdatePositionTimeStampOk returns a tuple with the UpdatePositionTimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAcccountRequestPositions) GetUpdatePositionTimeStampOk() (*float32, bool) {
	if o == nil || o.UpdatePositionTimeStamp == nil {
		return nil, false
	}
	return o.UpdatePositionTimeStamp, true
}

// HasUpdatePositionTimeStamp returns a boolean if a field has been set.
func (o *GetAcccountRequestPositions) HasUpdatePositionTimeStamp() bool {
	if o != nil && o.UpdatePositionTimeStamp != nil {
		return true
	}

	return false
}

// SetUpdatePositionTimeStamp gets a reference to the given float32 and assigns it to the UpdatePositionTimeStamp field.
func (o *GetAcccountRequestPositions) SetUpdatePositionTimeStamp(v float32) {
	o.UpdatePositionTimeStamp = &v
}

func (o GetAcccountRequestPositions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AssetType != nil {
		toSerialize["assetType"] = o.AssetType
	}
	if o.BrokerId != nil {
		toSerialize["brokerId"] = o.BrokerId
	}
	if o.Cost != nil {
		toSerialize["cost"] = o.Cost
	}
	if o.CostPrice != nil {
		toSerialize["costPrice"] = o.CostPrice
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.ExchangeRate != nil {
		toSerialize["exchangeRate"] = o.ExchangeRate
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.LastOpenTime != nil {
		toSerialize["lastOpenTime"] = o.LastOpenTime
	}
	if o.LastPrice != nil {
		toSerialize["lastPrice"] = o.LastPrice
	}
	if o.Lock != nil {
		toSerialize["lock"] = o.Lock
	}
	if o.MarketValue != nil {
		toSerialize["marketValue"] = o.MarketValue
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.PositionProportion != nil {
		toSerialize["positionProportion"] = o.PositionProportion
	}
	if o.Ticker != nil {
		toSerialize["ticker"] = o.Ticker
	}
	if o.UnrealizedProfitLoss != nil {
		toSerialize["unrealizedProfitLoss"] = o.UnrealizedProfitLoss
	}
	if o.UnrealizedProfitLossRate != nil {
		toSerialize["unrealizedProfitLossRate"] = o.UnrealizedProfitLossRate
	}
	if o.UpdatePositionTimeStamp != nil {
		toSerialize["updatePositionTimeStamp"] = o.UpdatePositionTimeStamp
	}
	return json.Marshal(toSerialize)
}

type NullableGetAcccountRequestPositions struct {
	value *GetAcccountRequestPositions
	isSet bool
}

func (v NullableGetAcccountRequestPositions) Get() *GetAcccountRequestPositions {
	return v.value
}

func (v *NullableGetAcccountRequestPositions) Set(val *GetAcccountRequestPositions) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAcccountRequestPositions) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAcccountRequestPositions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAcccountRequestPositions(val *GetAcccountRequestPositions) *NullableGetAcccountRequestPositions {
	return &NullableGetAcccountRequestPositions{value: val, isSet: true}
}

func (v NullableGetAcccountRequestPositions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAcccountRequestPositions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


