/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostLoginResponseExtInfo struct for PostLoginResponseExtInfo
type PostLoginResponseExtInfo struct {
	UserPwdFlag *string `json:"userPwdFlag,omitempty"`
}

// NewPostLoginResponseExtInfo instantiates a new PostLoginResponseExtInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostLoginResponseExtInfo() *PostLoginResponseExtInfo {
	this := PostLoginResponseExtInfo{}
	return &this
}

// NewPostLoginResponseExtInfoWithDefaults instantiates a new PostLoginResponseExtInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostLoginResponseExtInfoWithDefaults() *PostLoginResponseExtInfo {
	this := PostLoginResponseExtInfo{}
	return &this
}

// GetUserPwdFlag returns the UserPwdFlag field value if set, zero value otherwise.
func (o *PostLoginResponseExtInfo) GetUserPwdFlag() string {
	if o == nil || o.UserPwdFlag == nil {
		var ret string
		return ret
	}
	return *o.UserPwdFlag
}

// GetUserPwdFlagOk returns a tuple with the UserPwdFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLoginResponseExtInfo) GetUserPwdFlagOk() (*string, bool) {
	if o == nil || o.UserPwdFlag == nil {
		return nil, false
	}
	return o.UserPwdFlag, true
}

// HasUserPwdFlag returns a boolean if a field has been set.
func (o *PostLoginResponseExtInfo) HasUserPwdFlag() bool {
	if o != nil && o.UserPwdFlag != nil {
		return true
	}

	return false
}

// SetUserPwdFlag gets a reference to the given string and assigns it to the UserPwdFlag field.
func (o *PostLoginResponseExtInfo) SetUserPwdFlag(v string) {
	o.UserPwdFlag = &v
}

func (o PostLoginResponseExtInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserPwdFlag != nil {
		toSerialize["userPwdFlag"] = o.UserPwdFlag
	}
	return json.Marshal(toSerialize)
}

type NullablePostLoginResponseExtInfo struct {
	value *PostLoginResponseExtInfo
	isSet bool
}

func (v NullablePostLoginResponseExtInfo) Get() *PostLoginResponseExtInfo {
	return v.value
}

func (v *NullablePostLoginResponseExtInfo) Set(val *PostLoginResponseExtInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePostLoginResponseExtInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePostLoginResponseExtInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostLoginResponseExtInfo(val *PostLoginResponseExtInfo) *NullablePostLoginResponseExtInfo {
	return &NullablePostLoginResponseExtInfo{value: val, isSet: true}
}

func (v NullablePostLoginResponseExtInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostLoginResponseExtInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


