/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetFundamentalsResponseDataPoints struct for GetFundamentalsResponseDataPoints
type GetFundamentalsResponseDataPoints struct {
	ValueActual *int32 `json:"valueActual,omitempty"`
	ValueForecast *int32 `json:"valueForecast,omitempty"`
	XAxis *string `json:"xAxis,omitempty"`
}

// NewGetFundamentalsResponseDataPoints instantiates a new GetFundamentalsResponseDataPoints object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFundamentalsResponseDataPoints() *GetFundamentalsResponseDataPoints {
	this := GetFundamentalsResponseDataPoints{}
	return &this
}

// NewGetFundamentalsResponseDataPointsWithDefaults instantiates a new GetFundamentalsResponseDataPoints object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFundamentalsResponseDataPointsWithDefaults() *GetFundamentalsResponseDataPoints {
	this := GetFundamentalsResponseDataPoints{}
	return &this
}

// GetValueActual returns the ValueActual field value if set, zero value otherwise.
func (o *GetFundamentalsResponseDataPoints) GetValueActual() int32 {
	if o == nil || o.ValueActual == nil {
		var ret int32
		return ret
	}
	return *o.ValueActual
}

// GetValueActualOk returns a tuple with the ValueActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseDataPoints) GetValueActualOk() (*int32, bool) {
	if o == nil || o.ValueActual == nil {
		return nil, false
	}
	return o.ValueActual, true
}

// HasValueActual returns a boolean if a field has been set.
func (o *GetFundamentalsResponseDataPoints) HasValueActual() bool {
	if o != nil && o.ValueActual != nil {
		return true
	}

	return false
}

// SetValueActual gets a reference to the given int32 and assigns it to the ValueActual field.
func (o *GetFundamentalsResponseDataPoints) SetValueActual(v int32) {
	o.ValueActual = &v
}

// GetValueForecast returns the ValueForecast field value if set, zero value otherwise.
func (o *GetFundamentalsResponseDataPoints) GetValueForecast() int32 {
	if o == nil || o.ValueForecast == nil {
		var ret int32
		return ret
	}
	return *o.ValueForecast
}

// GetValueForecastOk returns a tuple with the ValueForecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseDataPoints) GetValueForecastOk() (*int32, bool) {
	if o == nil || o.ValueForecast == nil {
		return nil, false
	}
	return o.ValueForecast, true
}

// HasValueForecast returns a boolean if a field has been set.
func (o *GetFundamentalsResponseDataPoints) HasValueForecast() bool {
	if o != nil && o.ValueForecast != nil {
		return true
	}

	return false
}

// SetValueForecast gets a reference to the given int32 and assigns it to the ValueForecast field.
func (o *GetFundamentalsResponseDataPoints) SetValueForecast(v int32) {
	o.ValueForecast = &v
}

// GetXAxis returns the XAxis field value if set, zero value otherwise.
func (o *GetFundamentalsResponseDataPoints) GetXAxis() string {
	if o == nil || o.XAxis == nil {
		var ret string
		return ret
	}
	return *o.XAxis
}

// GetXAxisOk returns a tuple with the XAxis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFundamentalsResponseDataPoints) GetXAxisOk() (*string, bool) {
	if o == nil || o.XAxis == nil {
		return nil, false
	}
	return o.XAxis, true
}

// HasXAxis returns a boolean if a field has been set.
func (o *GetFundamentalsResponseDataPoints) HasXAxis() bool {
	if o != nil && o.XAxis != nil {
		return true
	}

	return false
}

// SetXAxis gets a reference to the given string and assigns it to the XAxis field.
func (o *GetFundamentalsResponseDataPoints) SetXAxis(v string) {
	o.XAxis = &v
}

func (o GetFundamentalsResponseDataPoints) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ValueActual != nil {
		toSerialize["valueActual"] = o.ValueActual
	}
	if o.ValueForecast != nil {
		toSerialize["valueForecast"] = o.ValueForecast
	}
	if o.XAxis != nil {
		toSerialize["xAxis"] = o.XAxis
	}
	return json.Marshal(toSerialize)
}

type NullableGetFundamentalsResponseDataPoints struct {
	value *GetFundamentalsResponseDataPoints
	isSet bool
}

func (v NullableGetFundamentalsResponseDataPoints) Get() *GetFundamentalsResponseDataPoints {
	return v.value
}

func (v *NullableGetFundamentalsResponseDataPoints) Set(val *GetFundamentalsResponseDataPoints) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFundamentalsResponseDataPoints) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFundamentalsResponseDataPoints) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFundamentalsResponseDataPoints(val *GetFundamentalsResponseDataPoints) *NullableGetFundamentalsResponseDataPoints {
	return &NullableGetFundamentalsResponseDataPoints{value: val, isSet: true}
}

func (v NullableGetFundamentalsResponseDataPoints) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFundamentalsResponseDataPoints) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


