/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAlertsResponse struct for GetAlertsResponse
type GetAlertsResponse struct {
	Code *string `json:"code,omitempty"`
	Data *[]GetAlertsResponseData `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// NewGetAlertsResponse instantiates a new GetAlertsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAlertsResponse() *GetAlertsResponse {
	this := GetAlertsResponse{}
	return &this
}

// NewGetAlertsResponseWithDefaults instantiates a new GetAlertsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAlertsResponseWithDefaults() *GetAlertsResponse {
	this := GetAlertsResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetAlertsResponse) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAlertsResponse) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetAlertsResponse) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetAlertsResponse) SetCode(v string) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAlertsResponse) GetData() []GetAlertsResponseData {
	if o == nil || o.Data == nil {
		var ret []GetAlertsResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAlertsResponse) GetDataOk() (*[]GetAlertsResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAlertsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetAlertsResponseData and assigns it to the Data field.
func (o *GetAlertsResponse) SetData(v []GetAlertsResponseData) {
	o.Data = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetAlertsResponse) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAlertsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetAlertsResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetAlertsResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o GetAlertsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableGetAlertsResponse struct {
	value *GetAlertsResponse
	isSet bool
}

func (v NullableGetAlertsResponse) Get() *GetAlertsResponse {
	return v.value
}

func (v *NullableGetAlertsResponse) Set(val *GetAlertsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAlertsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAlertsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAlertsResponse(val *GetAlertsResponse) *NullableGetAlertsResponse {
	return &NullableGetAlertsResponse{value: val, isSet: true}
}

func (v NullableGetAlertsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAlertsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


