/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostPaperTradeResponse struct for PostPaperTradeResponse
type PostPaperTradeResponse struct {
	OrderId int32 `json:"orderId,omitempty"`
}
