/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostRefreshTokenResponse struct for PostRefreshTokenResponse
type PostRefreshTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	TokenExpireTime *string `json:"tokenExpireTime,omitempty"`
}

// NewPostRefreshTokenResponse instantiates a new PostRefreshTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRefreshTokenResponse() *PostRefreshTokenResponse {
	this := PostRefreshTokenResponse{}
	return &this
}

// NewPostRefreshTokenResponseWithDefaults instantiates a new PostRefreshTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRefreshTokenResponseWithDefaults() *PostRefreshTokenResponse {
	this := PostRefreshTokenResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *PostRefreshTokenResponse) GetAccessToken() string {
	if o == nil || o.AccessToken == nil {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostRefreshTokenResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || o.AccessToken == nil {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *PostRefreshTokenResponse) HasAccessToken() bool {
	if o != nil && o.AccessToken != nil {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *PostRefreshTokenResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *PostRefreshTokenResponse) GetRefreshToken() string {
	if o == nil || o.RefreshToken == nil {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostRefreshTokenResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil || o.RefreshToken == nil {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *PostRefreshTokenResponse) HasRefreshToken() bool {
	if o != nil && o.RefreshToken != nil {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *PostRefreshTokenResponse) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

// GetTokenExpireTime returns the TokenExpireTime field value if set, zero value otherwise.
func (o *PostRefreshTokenResponse) GetTokenExpireTime() string {
	if o == nil || o.TokenExpireTime == nil {
		var ret string
		return ret
	}
	return *o.TokenExpireTime
}

// GetTokenExpireTimeOk returns a tuple with the TokenExpireTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostRefreshTokenResponse) GetTokenExpireTimeOk() (*string, bool) {
	if o == nil || o.TokenExpireTime == nil {
		return nil, false
	}
	return o.TokenExpireTime, true
}

// HasTokenExpireTime returns a boolean if a field has been set.
func (o *PostRefreshTokenResponse) HasTokenExpireTime() bool {
	if o != nil && o.TokenExpireTime != nil {
		return true
	}

	return false
}

// SetTokenExpireTime gets a reference to the given string and assigns it to the TokenExpireTime field.
func (o *PostRefreshTokenResponse) SetTokenExpireTime(v string) {
	o.TokenExpireTime = &v
}

func (o PostRefreshTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccessToken != nil {
		toSerialize["accessToken"] = o.AccessToken
	}
	if o.RefreshToken != nil {
		toSerialize["refreshToken"] = o.RefreshToken
	}
	if o.TokenExpireTime != nil {
		toSerialize["tokenExpireTime"] = o.TokenExpireTime
	}
	return json.Marshal(toSerialize)
}

type NullablePostRefreshTokenResponse struct {
	value *PostRefreshTokenResponse
	isSet bool
}

func (v NullablePostRefreshTokenResponse) Get() *PostRefreshTokenResponse {
	return v.value
}

func (v *NullablePostRefreshTokenResponse) Set(val *PostRefreshTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRefreshTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRefreshTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRefreshTokenResponse(val *PostRefreshTokenResponse) *NullablePostRefreshTokenResponse {
	return &NullablePostRefreshTokenResponse{value: val, isSet: true}
}

func (v NullablePostRefreshTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRefreshTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


