/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetStockAnalysisResponseForecastEpsPoints struct for GetStockAnalysisResponseForecastEpsPoints
type GetStockAnalysisResponseForecastEpsPoints struct {
	ValueActual *float32 `json:"valueActual,omitempty"`
	ValueForecast *float32 `json:"valueForecast,omitempty"`
	XAxis *string `json:"xAxis,omitempty"`
}

// NewGetStockAnalysisResponseForecastEpsPoints instantiates a new GetStockAnalysisResponseForecastEpsPoints object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStockAnalysisResponseForecastEpsPoints() *GetStockAnalysisResponseForecastEpsPoints {
	this := GetStockAnalysisResponseForecastEpsPoints{}
	return &this
}

// NewGetStockAnalysisResponseForecastEpsPointsWithDefaults instantiates a new GetStockAnalysisResponseForecastEpsPoints object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStockAnalysisResponseForecastEpsPointsWithDefaults() *GetStockAnalysisResponseForecastEpsPoints {
	this := GetStockAnalysisResponseForecastEpsPoints{}
	return &this
}

// GetValueActual returns the ValueActual field value if set, zero value otherwise.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetValueActual() float32 {
	if o == nil || o.ValueActual == nil {
		var ret float32
		return ret
	}
	return *o.ValueActual
}

// GetValueActualOk returns a tuple with the ValueActual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetValueActualOk() (*float32, bool) {
	if o == nil || o.ValueActual == nil {
		return nil, false
	}
	return o.ValueActual, true
}

// HasValueActual returns a boolean if a field has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) HasValueActual() bool {
	if o != nil && o.ValueActual != nil {
		return true
	}

	return false
}

// SetValueActual gets a reference to the given float32 and assigns it to the ValueActual field.
func (o *GetStockAnalysisResponseForecastEpsPoints) SetValueActual(v float32) {
	o.ValueActual = &v
}

// GetValueForecast returns the ValueForecast field value if set, zero value otherwise.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetValueForecast() float32 {
	if o == nil || o.ValueForecast == nil {
		var ret float32
		return ret
	}
	return *o.ValueForecast
}

// GetValueForecastOk returns a tuple with the ValueForecast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetValueForecastOk() (*float32, bool) {
	if o == nil || o.ValueForecast == nil {
		return nil, false
	}
	return o.ValueForecast, true
}

// HasValueForecast returns a boolean if a field has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) HasValueForecast() bool {
	if o != nil && o.ValueForecast != nil {
		return true
	}

	return false
}

// SetValueForecast gets a reference to the given float32 and assigns it to the ValueForecast field.
func (o *GetStockAnalysisResponseForecastEpsPoints) SetValueForecast(v float32) {
	o.ValueForecast = &v
}

// GetXAxis returns the XAxis field value if set, zero value otherwise.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetXAxis() string {
	if o == nil || o.XAxis == nil {
		var ret string
		return ret
	}
	return *o.XAxis
}

// GetXAxisOk returns a tuple with the XAxis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) GetXAxisOk() (*string, bool) {
	if o == nil || o.XAxis == nil {
		return nil, false
	}
	return o.XAxis, true
}

// HasXAxis returns a boolean if a field has been set.
func (o *GetStockAnalysisResponseForecastEpsPoints) HasXAxis() bool {
	if o != nil && o.XAxis != nil {
		return true
	}

	return false
}

// SetXAxis gets a reference to the given string and assigns it to the XAxis field.
func (o *GetStockAnalysisResponseForecastEpsPoints) SetXAxis(v string) {
	o.XAxis = &v
}

func (o GetStockAnalysisResponseForecastEpsPoints) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ValueActual != nil {
		toSerialize["valueActual"] = o.ValueActual
	}
	if o.ValueForecast != nil {
		toSerialize["valueForecast"] = o.ValueForecast
	}
	if o.XAxis != nil {
		toSerialize["xAxis"] = o.XAxis
	}
	return json.Marshal(toSerialize)
}

type NullableGetStockAnalysisResponseForecastEpsPoints struct {
	value *GetStockAnalysisResponseForecastEpsPoints
	isSet bool
}

func (v NullableGetStockAnalysisResponseForecastEpsPoints) Get() *GetStockAnalysisResponseForecastEpsPoints {
	return v.value
}

func (v *NullableGetStockAnalysisResponseForecastEpsPoints) Set(val *GetStockAnalysisResponseForecastEpsPoints) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStockAnalysisResponseForecastEpsPoints) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStockAnalysisResponseForecastEpsPoints) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStockAnalysisResponseForecastEpsPoints(val *GetStockAnalysisResponseForecastEpsPoints) *NullableGetStockAnalysisResponseForecastEpsPoints {
	return &NullableGetStockAnalysisResponseForecastEpsPoints{value: val, isSet: true}
}

func (v NullableGetStockAnalysisResponseForecastEpsPoints) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStockAnalysisResponseForecastEpsPoints) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


