/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAlertsResponseEventWarning struct for GetAlertsResponseEventWarning
type GetAlertsResponseEventWarning struct {
	Del bool `json:"del,omitempty"`
	ExchangeId float32 `json:"exchangeId,omitempty"`
	Id float32 `json:"id,omitempty"`
	Remove bool `json:"remove,omitempty"`
	Rules []GetAlertsResponseEventWarningRules `json:"rules,omitempty"`
	TickerId float32 `json:"tickerId,omitempty"`
	TickerType float32 `json:"tickerType,omitempty"`
	UserId float32 `json:"userId,omitempty"`
}
