/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAccountResponse struct for GetAccountResponse
type GetAccountResponse struct {
	AccountMembers *[]GetAcccountRequestAccountMembers `json:"accountMembers,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	Banners *[]GetAcccountRequestBanners `json:"banners,omitempty"`
	BrokerAccountId *string `json:"brokerAccountId,omitempty"`
	BrokerId *int32 `json:"brokerId,omitempty"`
	Currency *string `json:"currency,omitempty"`
	CurrencyId *int32 `json:"currencyId,omitempty"`
	Deposits *[]map[string]interface{} `json:"deposits,omitempty"`
	NetLiquidation *string `json:"netLiquidation,omitempty"`
	OpenIpoOrders *[]map[string]interface{} `json:"openIpoOrders,omitempty"`
	OpenOrderSize *int32 `json:"openOrderSize,omitempty"`
	OpenOrders *[]map[string]interface{} `json:"openOrders,omitempty"`
	Pdt *bool `json:"pdt,omitempty"`
	Positions *[]GetAccountResponsePositions `json:"positions,omitempty"`
	Professional *bool `json:"professional,omitempty"`
	SecAccountId *int32 `json:"secAccountId,omitempty"`
	ShowUpgrade *bool `json:"showUpgrade,omitempty"`
	TotalCost *string `json:"totalCost,omitempty"`
	UnrealizedProfitLoss *string `json:"unrealizedProfitLoss,omitempty"`
	UnrealizedProfitLossBase *float32 `json:"unrealizedProfitLossBase,omitempty"`
	UnrealizedProfitLossRate *string `json:"unrealizedProfitLossRate,omitempty"`
	Warning *bool `json:"warning,omitempty"`
}

// NewGetAccountResponse instantiates a new GetAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountResponse() *GetAccountResponse {
	this := GetAccountResponse{}
	return &this
}

// NewGetAccountResponseWithDefaults instantiates a new GetAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountResponseWithDefaults() *GetAccountResponse {
	this := GetAccountResponse{}
	return &this
}

// GetAccountMembers returns the AccountMembers field value if set, zero value otherwise.
func (o *GetAccountResponse) GetAccountMembers() []GetAcccountRequestAccountMembers {
	if o == nil || o.AccountMembers == nil {
		var ret []GetAcccountRequestAccountMembers
		return ret
	}
	return *o.AccountMembers
}

// GetAccountMembersOk returns a tuple with the AccountMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetAccountMembersOk() (*[]GetAcccountRequestAccountMembers, bool) {
	if o == nil || o.AccountMembers == nil {
		return nil, false
	}
	return o.AccountMembers, true
}

// HasAccountMembers returns a boolean if a field has been set.
func (o *GetAccountResponse) HasAccountMembers() bool {
	if o != nil && o.AccountMembers != nil {
		return true
	}

	return false
}

// SetAccountMembers gets a reference to the given []GetAcccountRequestAccountMembers and assigns it to the AccountMembers field.
func (o *GetAccountResponse) SetAccountMembers(v []GetAcccountRequestAccountMembers) {
	o.AccountMembers = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *GetAccountResponse) GetAccountType() string {
	if o == nil || o.AccountType == nil {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetAccountTypeOk() (*string, bool) {
	if o == nil || o.AccountType == nil {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *GetAccountResponse) HasAccountType() bool {
	if o != nil && o.AccountType != nil {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *GetAccountResponse) SetAccountType(v string) {
	o.AccountType = &v
}

// GetBanners returns the Banners field value if set, zero value otherwise.
func (o *GetAccountResponse) GetBanners() []GetAcccountRequestBanners {
	if o == nil || o.Banners == nil {
		var ret []GetAcccountRequestBanners
		return ret
	}
	return *o.Banners
}

// GetBannersOk returns a tuple with the Banners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetBannersOk() (*[]GetAcccountRequestBanners, bool) {
	if o == nil || o.Banners == nil {
		return nil, false
	}
	return o.Banners, true
}

// HasBanners returns a boolean if a field has been set.
func (o *GetAccountResponse) HasBanners() bool {
	if o != nil && o.Banners != nil {
		return true
	}

	return false
}

// SetBanners gets a reference to the given []GetAcccountRequestBanners and assigns it to the Banners field.
func (o *GetAccountResponse) SetBanners(v []GetAcccountRequestBanners) {
	o.Banners = &v
}

// GetBrokerAccountId returns the BrokerAccountId field value if set, zero value otherwise.
func (o *GetAccountResponse) GetBrokerAccountId() string {
	if o == nil || o.BrokerAccountId == nil {
		var ret string
		return ret
	}
	return *o.BrokerAccountId
}

// GetBrokerAccountIdOk returns a tuple with the BrokerAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetBrokerAccountIdOk() (*string, bool) {
	if o == nil || o.BrokerAccountId == nil {
		return nil, false
	}
	return o.BrokerAccountId, true
}

// HasBrokerAccountId returns a boolean if a field has been set.
func (o *GetAccountResponse) HasBrokerAccountId() bool {
	if o != nil && o.BrokerAccountId != nil {
		return true
	}

	return false
}

// SetBrokerAccountId gets a reference to the given string and assigns it to the BrokerAccountId field.
func (o *GetAccountResponse) SetBrokerAccountId(v string) {
	o.BrokerAccountId = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetAccountResponse) GetBrokerId() int32 {
	if o == nil || o.BrokerId == nil {
		var ret int32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetBrokerIdOk() (*int32, bool) {
	if o == nil || o.BrokerId == nil {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetAccountResponse) HasBrokerId() bool {
	if o != nil && o.BrokerId != nil {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given int32 and assigns it to the BrokerId field.
func (o *GetAccountResponse) SetBrokerId(v int32) {
	o.BrokerId = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetAccountResponse) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetAccountResponse) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetAccountResponse) SetCurrency(v string) {
	o.Currency = &v
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise.
func (o *GetAccountResponse) GetCurrencyId() int32 {
	if o == nil || o.CurrencyId == nil {
		var ret int32
		return ret
	}
	return *o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetCurrencyIdOk() (*int32, bool) {
	if o == nil || o.CurrencyId == nil {
		return nil, false
	}
	return o.CurrencyId, true
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *GetAccountResponse) HasCurrencyId() bool {
	if o != nil && o.CurrencyId != nil {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given int32 and assigns it to the CurrencyId field.
func (o *GetAccountResponse) SetCurrencyId(v int32) {
	o.CurrencyId = &v
}

// GetDeposits returns the Deposits field value if set, zero value otherwise.
func (o *GetAccountResponse) GetDeposits() []map[string]interface{} {
	if o == nil || o.Deposits == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Deposits
}

// GetDepositsOk returns a tuple with the Deposits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetDepositsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Deposits == nil {
		return nil, false
	}
	return o.Deposits, true
}

// HasDeposits returns a boolean if a field has been set.
func (o *GetAccountResponse) HasDeposits() bool {
	if o != nil && o.Deposits != nil {
		return true
	}

	return false
}

// SetDeposits gets a reference to the given []map[string]interface{} and assigns it to the Deposits field.
func (o *GetAccountResponse) SetDeposits(v []map[string]interface{}) {
	o.Deposits = &v
}

// GetNetLiquidation returns the NetLiquidation field value if set, zero value otherwise.
func (o *GetAccountResponse) GetNetLiquidation() string {
	if o == nil || o.NetLiquidation == nil {
		var ret string
		return ret
	}
	return *o.NetLiquidation
}

// GetNetLiquidationOk returns a tuple with the NetLiquidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetNetLiquidationOk() (*string, bool) {
	if o == nil || o.NetLiquidation == nil {
		return nil, false
	}
	return o.NetLiquidation, true
}

// HasNetLiquidation returns a boolean if a field has been set.
func (o *GetAccountResponse) HasNetLiquidation() bool {
	if o != nil && o.NetLiquidation != nil {
		return true
	}

	return false
}

// SetNetLiquidation gets a reference to the given string and assigns it to the NetLiquidation field.
func (o *GetAccountResponse) SetNetLiquidation(v string) {
	o.NetLiquidation = &v
}

// GetOpenIpoOrders returns the OpenIpoOrders field value if set, zero value otherwise.
func (o *GetAccountResponse) GetOpenIpoOrders() []map[string]interface{} {
	if o == nil || o.OpenIpoOrders == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.OpenIpoOrders
}

// GetOpenIpoOrdersOk returns a tuple with the OpenIpoOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetOpenIpoOrdersOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.OpenIpoOrders == nil {
		return nil, false
	}
	return o.OpenIpoOrders, true
}

// HasOpenIpoOrders returns a boolean if a field has been set.
func (o *GetAccountResponse) HasOpenIpoOrders() bool {
	if o != nil && o.OpenIpoOrders != nil {
		return true
	}

	return false
}

// SetOpenIpoOrders gets a reference to the given []map[string]interface{} and assigns it to the OpenIpoOrders field.
func (o *GetAccountResponse) SetOpenIpoOrders(v []map[string]interface{}) {
	o.OpenIpoOrders = &v
}

// GetOpenOrderSize returns the OpenOrderSize field value if set, zero value otherwise.
func (o *GetAccountResponse) GetOpenOrderSize() int32 {
	if o == nil || o.OpenOrderSize == nil {
		var ret int32
		return ret
	}
	return *o.OpenOrderSize
}

// GetOpenOrderSizeOk returns a tuple with the OpenOrderSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetOpenOrderSizeOk() (*int32, bool) {
	if o == nil || o.OpenOrderSize == nil {
		return nil, false
	}
	return o.OpenOrderSize, true
}

// HasOpenOrderSize returns a boolean if a field has been set.
func (o *GetAccountResponse) HasOpenOrderSize() bool {
	if o != nil && o.OpenOrderSize != nil {
		return true
	}

	return false
}

// SetOpenOrderSize gets a reference to the given int32 and assigns it to the OpenOrderSize field.
func (o *GetAccountResponse) SetOpenOrderSize(v int32) {
	o.OpenOrderSize = &v
}

// GetOpenOrders returns the OpenOrders field value if set, zero value otherwise.
func (o *GetAccountResponse) GetOpenOrders() []map[string]interface{} {
	if o == nil || o.OpenOrders == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.OpenOrders
}

// GetOpenOrdersOk returns a tuple with the OpenOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetOpenOrdersOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.OpenOrders == nil {
		return nil, false
	}
	return o.OpenOrders, true
}

// HasOpenOrders returns a boolean if a field has been set.
func (o *GetAccountResponse) HasOpenOrders() bool {
	if o != nil && o.OpenOrders != nil {
		return true
	}

	return false
}

// SetOpenOrders gets a reference to the given []map[string]interface{} and assigns it to the OpenOrders field.
func (o *GetAccountResponse) SetOpenOrders(v []map[string]interface{}) {
	o.OpenOrders = &v
}

// GetPdt returns the Pdt field value if set, zero value otherwise.
func (o *GetAccountResponse) GetPdt() bool {
	if o == nil || o.Pdt == nil {
		var ret bool
		return ret
	}
	return *o.Pdt
}

// GetPdtOk returns a tuple with the Pdt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetPdtOk() (*bool, bool) {
	if o == nil || o.Pdt == nil {
		return nil, false
	}
	return o.Pdt, true
}

// HasPdt returns a boolean if a field has been set.
func (o *GetAccountResponse) HasPdt() bool {
	if o != nil && o.Pdt != nil {
		return true
	}

	return false
}

// SetPdt gets a reference to the given bool and assigns it to the Pdt field.
func (o *GetAccountResponse) SetPdt(v bool) {
	o.Pdt = &v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *GetAccountResponse) GetPositions() []GetAccountResponsePositions {
	if o == nil || o.Positions == nil {
		var ret []GetAccountResponsePositions
		return ret
	}
	return *o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetPositionsOk() (*[]GetAccountResponsePositions, bool) {
	if o == nil || o.Positions == nil {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *GetAccountResponse) HasPositions() bool {
	if o != nil && o.Positions != nil {
		return true
	}

	return false
}

// SetPositions gets a reference to the given []GetAccountResponsePositions and assigns it to the Positions field.
func (o *GetAccountResponse) SetPositions(v []GetAccountResponsePositions) {
	o.Positions = &v
}

// GetProfessional returns the Professional field value if set, zero value otherwise.
func (o *GetAccountResponse) GetProfessional() bool {
	if o == nil || o.Professional == nil {
		var ret bool
		return ret
	}
	return *o.Professional
}

// GetProfessionalOk returns a tuple with the Professional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetProfessionalOk() (*bool, bool) {
	if o == nil || o.Professional == nil {
		return nil, false
	}
	return o.Professional, true
}

// HasProfessional returns a boolean if a field has been set.
func (o *GetAccountResponse) HasProfessional() bool {
	if o != nil && o.Professional != nil {
		return true
	}

	return false
}

// SetProfessional gets a reference to the given bool and assigns it to the Professional field.
func (o *GetAccountResponse) SetProfessional(v bool) {
	o.Professional = &v
}

// GetSecAccountId returns the SecAccountId field value if set, zero value otherwise.
func (o *GetAccountResponse) GetSecAccountId() int32 {
	if o == nil || o.SecAccountId == nil {
		var ret int32
		return ret
	}
	return *o.SecAccountId
}

// GetSecAccountIdOk returns a tuple with the SecAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetSecAccountIdOk() (*int32, bool) {
	if o == nil || o.SecAccountId == nil {
		return nil, false
	}
	return o.SecAccountId, true
}

// HasSecAccountId returns a boolean if a field has been set.
func (o *GetAccountResponse) HasSecAccountId() bool {
	if o != nil && o.SecAccountId != nil {
		return true
	}

	return false
}

// SetSecAccountId gets a reference to the given int32 and assigns it to the SecAccountId field.
func (o *GetAccountResponse) SetSecAccountId(v int32) {
	o.SecAccountId = &v
}

// GetShowUpgrade returns the ShowUpgrade field value if set, zero value otherwise.
func (o *GetAccountResponse) GetShowUpgrade() bool {
	if o == nil || o.ShowUpgrade == nil {
		var ret bool
		return ret
	}
	return *o.ShowUpgrade
}

// GetShowUpgradeOk returns a tuple with the ShowUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetShowUpgradeOk() (*bool, bool) {
	if o == nil || o.ShowUpgrade == nil {
		return nil, false
	}
	return o.ShowUpgrade, true
}

// HasShowUpgrade returns a boolean if a field has been set.
func (o *GetAccountResponse) HasShowUpgrade() bool {
	if o != nil && o.ShowUpgrade != nil {
		return true
	}

	return false
}

// SetShowUpgrade gets a reference to the given bool and assigns it to the ShowUpgrade field.
func (o *GetAccountResponse) SetShowUpgrade(v bool) {
	o.ShowUpgrade = &v
}

// GetTotalCost returns the TotalCost field value if set, zero value otherwise.
func (o *GetAccountResponse) GetTotalCost() string {
	if o == nil || o.TotalCost == nil {
		var ret string
		return ret
	}
	return *o.TotalCost
}

// GetTotalCostOk returns a tuple with the TotalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetTotalCostOk() (*string, bool) {
	if o == nil || o.TotalCost == nil {
		return nil, false
	}
	return o.TotalCost, true
}

// HasTotalCost returns a boolean if a field has been set.
func (o *GetAccountResponse) HasTotalCost() bool {
	if o != nil && o.TotalCost != nil {
		return true
	}

	return false
}

// SetTotalCost gets a reference to the given string and assigns it to the TotalCost field.
func (o *GetAccountResponse) SetTotalCost(v string) {
	o.TotalCost = &v
}

// GetUnrealizedProfitLoss returns the UnrealizedProfitLoss field value if set, zero value otherwise.
func (o *GetAccountResponse) GetUnrealizedProfitLoss() string {
	if o == nil || o.UnrealizedProfitLoss == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLoss
}

// GetUnrealizedProfitLossOk returns a tuple with the UnrealizedProfitLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetUnrealizedProfitLossOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLoss == nil {
		return nil, false
	}
	return o.UnrealizedProfitLoss, true
}

// HasUnrealizedProfitLoss returns a boolean if a field has been set.
func (o *GetAccountResponse) HasUnrealizedProfitLoss() bool {
	if o != nil && o.UnrealizedProfitLoss != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLoss gets a reference to the given string and assigns it to the UnrealizedProfitLoss field.
func (o *GetAccountResponse) SetUnrealizedProfitLoss(v string) {
	o.UnrealizedProfitLoss = &v
}

// GetUnrealizedProfitLossBase returns the UnrealizedProfitLossBase field value if set, zero value otherwise.
func (o *GetAccountResponse) GetUnrealizedProfitLossBase() float32 {
	if o == nil || o.UnrealizedProfitLossBase == nil {
		var ret float32
		return ret
	}
	return *o.UnrealizedProfitLossBase
}

// GetUnrealizedProfitLossBaseOk returns a tuple with the UnrealizedProfitLossBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetUnrealizedProfitLossBaseOk() (*float32, bool) {
	if o == nil || o.UnrealizedProfitLossBase == nil {
		return nil, false
	}
	return o.UnrealizedProfitLossBase, true
}

// HasUnrealizedProfitLossBase returns a boolean if a field has been set.
func (o *GetAccountResponse) HasUnrealizedProfitLossBase() bool {
	if o != nil && o.UnrealizedProfitLossBase != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLossBase gets a reference to the given float32 and assigns it to the UnrealizedProfitLossBase field.
func (o *GetAccountResponse) SetUnrealizedProfitLossBase(v float32) {
	o.UnrealizedProfitLossBase = &v
}

// GetUnrealizedProfitLossRate returns the UnrealizedProfitLossRate field value if set, zero value otherwise.
func (o *GetAccountResponse) GetUnrealizedProfitLossRate() string {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		var ret string
		return ret
	}
	return *o.UnrealizedProfitLossRate
}

// GetUnrealizedProfitLossRateOk returns a tuple with the UnrealizedProfitLossRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetUnrealizedProfitLossRateOk() (*string, bool) {
	if o == nil || o.UnrealizedProfitLossRate == nil {
		return nil, false
	}
	return o.UnrealizedProfitLossRate, true
}

// HasUnrealizedProfitLossRate returns a boolean if a field has been set.
func (o *GetAccountResponse) HasUnrealizedProfitLossRate() bool {
	if o != nil && o.UnrealizedProfitLossRate != nil {
		return true
	}

	return false
}

// SetUnrealizedProfitLossRate gets a reference to the given string and assigns it to the UnrealizedProfitLossRate field.
func (o *GetAccountResponse) SetUnrealizedProfitLossRate(v string) {
	o.UnrealizedProfitLossRate = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *GetAccountResponse) GetWarning() bool {
	if o == nil || o.Warning == nil {
		var ret bool
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetWarningOk() (*bool, bool) {
	if o == nil || o.Warning == nil {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *GetAccountResponse) HasWarning() bool {
	if o != nil && o.Warning != nil {
		return true
	}

	return false
}

// SetWarning gets a reference to the given bool and assigns it to the Warning field.
func (o *GetAccountResponse) SetWarning(v bool) {
	o.Warning = &v
}

func (o GetAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountMembers != nil {
		toSerialize["accountMembers"] = o.AccountMembers
	}
	if o.AccountType != nil {
		toSerialize["accountType"] = o.AccountType
	}
	if o.Banners != nil {
		toSerialize["banners"] = o.Banners
	}
	if o.BrokerAccountId != nil {
		toSerialize["brokerAccountId"] = o.BrokerAccountId
	}
	if o.BrokerId != nil {
		toSerialize["brokerId"] = o.BrokerId
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.CurrencyId != nil {
		toSerialize["currencyId"] = o.CurrencyId
	}
	if o.Deposits != nil {
		toSerialize["deposits"] = o.Deposits
	}
	if o.NetLiquidation != nil {
		toSerialize["netLiquidation"] = o.NetLiquidation
	}
	if o.OpenIpoOrders != nil {
		toSerialize["openIpoOrders"] = o.OpenIpoOrders
	}
	if o.OpenOrderSize != nil {
		toSerialize["openOrderSize"] = o.OpenOrderSize
	}
	if o.OpenOrders != nil {
		toSerialize["openOrders"] = o.OpenOrders
	}
	if o.Pdt != nil {
		toSerialize["pdt"] = o.Pdt
	}
	if o.Positions != nil {
		toSerialize["positions"] = o.Positions
	}
	if o.Professional != nil {
		toSerialize["professional"] = o.Professional
	}
	if o.SecAccountId != nil {
		toSerialize["secAccountId"] = o.SecAccountId
	}
	if o.ShowUpgrade != nil {
		toSerialize["showUpgrade"] = o.ShowUpgrade
	}
	if o.TotalCost != nil {
		toSerialize["totalCost"] = o.TotalCost
	}
	if o.UnrealizedProfitLoss != nil {
		toSerialize["unrealizedProfitLoss"] = o.UnrealizedProfitLoss
	}
	if o.UnrealizedProfitLossBase != nil {
		toSerialize["unrealizedProfitLossBase"] = o.UnrealizedProfitLossBase
	}
	if o.UnrealizedProfitLossRate != nil {
		toSerialize["unrealizedProfitLossRate"] = o.UnrealizedProfitLossRate
	}
	if o.Warning != nil {
		toSerialize["warning"] = o.Warning
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountResponse struct {
	value *GetAccountResponse
	isSet bool
}

func (v NullableGetAccountResponse) Get() *GetAccountResponse {
	return v.value
}

func (v *NullableGetAccountResponse) Set(val *GetAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountResponse(val *GetAccountResponse) *NullableGetAccountResponse {
	return &NullableGetAccountResponse{value: val, isSet: true}
}

func (v NullableGetAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


