/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetNewsResponseItems struct for GetNewsResponseItems
type GetNewsResponseItems struct {
	CollectSource string `json:"collectSource,omitempty"`
	Id float32 `json:"id,omitempty"`
	NewsTime string `json:"newsTime,omitempty"`
	NewsUrl string `json:"newsUrl,omitempty"`
	SiteType float32 `json:"siteType,omitempty"`
	SourceName string `json:"sourceName,omitempty"`
	Summary string `json:"summary,omitempty"`
	Title string `json:"title,omitempty"`
}
