/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetOrdersItemOrders struct for GetOrdersItemOrders
type GetOrdersItemOrders struct {
	Action *OrderSide `json:"action,omitempty"`
	AssetType *string `json:"assetType,omitempty"`
	AvgFilledPrice *string `json:"avgFilledPrice,omitempty"`
	BrokerId *int32 `json:"brokerId,omitempty"`
	CanCancel *bool `json:"canCancel,omitempty"`
	CanModify *bool `json:"canModify,omitempty"`
	CreateTime *string `json:"createTime,omitempty"`
	CreateTime0 *int64 `json:"createTime0,omitempty"`
	FilledQuantity *string `json:"filledQuantity,omitempty"`
	FilledTime *string `json:"filledTime,omitempty"`
	FilledTime0 *float32 `json:"filledTime0,omitempty"`
	FilledValue *string `json:"filledValue,omitempty"`
	OptionContractMultiplier *string `json:"optionContractMultiplier,omitempty"`
	OptionExercisePrice *string `json:"optionExercisePrice,omitempty"`
	OptionCycle *int64 `json:"optionCycle,omitempty"`
	OrderId *int32 `json:"orderId,omitempty"`
	OrderType *OrderType `json:"orderType,omitempty"`
	OptionType *OptionType `json:"optionType,omitempty"`
	OptionExpirationDate *string `json:"optionExpirationDate,omitempty"`
	Relation *string `json:"relation,omitempty"`
	OptionCategory *string `json:"optionCategory,omitempty"`
	RemainQuantity *string `json:"remainQuantity,omitempty"`
	StatusCode *string `json:"statusCode,omitempty"`
	StatusStr *string `json:"statusStr,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	Ticker *GetOrdersItemTicker `json:"ticker,omitempty"`
	TickerId *int32 `json:"tickerId,omitempty"`
	TickerPriceDefineList *[]GetOrdersItemTickerPriceDefineList `json:"tickerPriceDefineList,omitempty"`
	TimeInForce *TimeInForce `json:"timeInForce,omitempty"`
	TotalQuantity *string `json:"totalQuantity,omitempty"`
	UpdateTime *string `json:"updateTime,omitempty"`
	UpdateTime0 *float32 `json:"updateTime0,omitempty"`
}

// NewGetOrdersItemOrders instantiates a new GetOrdersItemOrders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrdersItemOrders() *GetOrdersItemOrders {
	this := GetOrdersItemOrders{}
	return &this
}

// NewGetOrdersItemOrdersWithDefaults instantiates a new GetOrdersItemOrders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrdersItemOrdersWithDefaults() *GetOrdersItemOrders {
	this := GetOrdersItemOrders{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetAction() OrderSide {
	if o == nil || o.Action == nil {
		var ret OrderSide
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetActionOk() (*OrderSide, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given OrderSide and assigns it to the Action field.
func (o *GetOrdersItemOrders) SetAction(v OrderSide) {
	o.Action = &v
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetAssetType() string {
	if o == nil || o.AssetType == nil {
		var ret string
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetAssetTypeOk() (*string, bool) {
	if o == nil || o.AssetType == nil {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasAssetType() bool {
	if o != nil && o.AssetType != nil {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given string and assigns it to the AssetType field.
func (o *GetOrdersItemOrders) SetAssetType(v string) {
	o.AssetType = &v
}

// GetAvgFilledPrice returns the AvgFilledPrice field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetAvgFilledPrice() string {
	if o == nil || o.AvgFilledPrice == nil {
		var ret string
		return ret
	}
	return *o.AvgFilledPrice
}

// GetAvgFilledPriceOk returns a tuple with the AvgFilledPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetAvgFilledPriceOk() (*string, bool) {
	if o == nil || o.AvgFilledPrice == nil {
		return nil, false
	}
	return o.AvgFilledPrice, true
}

// HasAvgFilledPrice returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasAvgFilledPrice() bool {
	if o != nil && o.AvgFilledPrice != nil {
		return true
	}

	return false
}

// SetAvgFilledPrice gets a reference to the given string and assigns it to the AvgFilledPrice field.
func (o *GetOrdersItemOrders) SetAvgFilledPrice(v string) {
	o.AvgFilledPrice = &v
}

// GetBrokerId returns the BrokerId field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetBrokerId() int32 {
	if o == nil || o.BrokerId == nil {
		var ret int32
		return ret
	}
	return *o.BrokerId
}

// GetBrokerIdOk returns a tuple with the BrokerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetBrokerIdOk() (*int32, bool) {
	if o == nil || o.BrokerId == nil {
		return nil, false
	}
	return o.BrokerId, true
}

// HasBrokerId returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasBrokerId() bool {
	if o != nil && o.BrokerId != nil {
		return true
	}

	return false
}

// SetBrokerId gets a reference to the given int32 and assigns it to the BrokerId field.
func (o *GetOrdersItemOrders) SetBrokerId(v int32) {
	o.BrokerId = &v
}

// GetCanCancel returns the CanCancel field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetCanCancel() bool {
	if o == nil || o.CanCancel == nil {
		var ret bool
		return ret
	}
	return *o.CanCancel
}

// GetCanCancelOk returns a tuple with the CanCancel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetCanCancelOk() (*bool, bool) {
	if o == nil || o.CanCancel == nil {
		return nil, false
	}
	return o.CanCancel, true
}

// HasCanCancel returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasCanCancel() bool {
	if o != nil && o.CanCancel != nil {
		return true
	}

	return false
}

// SetCanCancel gets a reference to the given bool and assigns it to the CanCancel field.
func (o *GetOrdersItemOrders) SetCanCancel(v bool) {
	o.CanCancel = &v
}

// GetCanModify returns the CanModify field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetCanModify() bool {
	if o == nil || o.CanModify == nil {
		var ret bool
		return ret
	}
	return *o.CanModify
}

// GetCanModifyOk returns a tuple with the CanModify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetCanModifyOk() (*bool, bool) {
	if o == nil || o.CanModify == nil {
		return nil, false
	}
	return o.CanModify, true
}

// HasCanModify returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasCanModify() bool {
	if o != nil && o.CanModify != nil {
		return true
	}

	return false
}

// SetCanModify gets a reference to the given bool and assigns it to the CanModify field.
func (o *GetOrdersItemOrders) SetCanModify(v bool) {
	o.CanModify = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetCreateTime() string {
	if o == nil || o.CreateTime == nil {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetCreateTimeOk() (*string, bool) {
	if o == nil || o.CreateTime == nil {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasCreateTime() bool {
	if o != nil && o.CreateTime != nil {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *GetOrdersItemOrders) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetCreateTime0 returns the CreateTime0 field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetCreateTime0() int64 {
	if o == nil || o.CreateTime0 == nil {
		var ret int64
		return ret
	}
	return *o.CreateTime0
}

// GetCreateTime0Ok returns a tuple with the CreateTime0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetCreateTime0Ok() (*int64, bool) {
	if o == nil || o.CreateTime0 == nil {
		return nil, false
	}
	return o.CreateTime0, true
}

// HasCreateTime0 returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasCreateTime0() bool {
	if o != nil && o.CreateTime0 != nil {
		return true
	}

	return false
}

// SetCreateTime0 gets a reference to the given int64 and assigns it to the CreateTime0 field.
func (o *GetOrdersItemOrders) SetCreateTime0(v int64) {
	o.CreateTime0 = &v
}

// GetFilledQuantity returns the FilledQuantity field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetFilledQuantity() string {
	if o == nil || o.FilledQuantity == nil {
		var ret string
		return ret
	}
	return *o.FilledQuantity
}

// GetFilledQuantityOk returns a tuple with the FilledQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetFilledQuantityOk() (*string, bool) {
	if o == nil || o.FilledQuantity == nil {
		return nil, false
	}
	return o.FilledQuantity, true
}

// HasFilledQuantity returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasFilledQuantity() bool {
	if o != nil && o.FilledQuantity != nil {
		return true
	}

	return false
}

// SetFilledQuantity gets a reference to the given string and assigns it to the FilledQuantity field.
func (o *GetOrdersItemOrders) SetFilledQuantity(v string) {
	o.FilledQuantity = &v
}

// GetFilledTime returns the FilledTime field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetFilledTime() string {
	if o == nil || o.FilledTime == nil {
		var ret string
		return ret
	}
	return *o.FilledTime
}

// GetFilledTimeOk returns a tuple with the FilledTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetFilledTimeOk() (*string, bool) {
	if o == nil || o.FilledTime == nil {
		return nil, false
	}
	return o.FilledTime, true
}

// HasFilledTime returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasFilledTime() bool {
	if o != nil && o.FilledTime != nil {
		return true
	}

	return false
}

// SetFilledTime gets a reference to the given string and assigns it to the FilledTime field.
func (o *GetOrdersItemOrders) SetFilledTime(v string) {
	o.FilledTime = &v
}

// GetFilledTime0 returns the FilledTime0 field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetFilledTime0() float32 {
	if o == nil || o.FilledTime0 == nil {
		var ret float32
		return ret
	}
	return *o.FilledTime0
}

// GetFilledTime0Ok returns a tuple with the FilledTime0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetFilledTime0Ok() (*float32, bool) {
	if o == nil || o.FilledTime0 == nil {
		return nil, false
	}
	return o.FilledTime0, true
}

// HasFilledTime0 returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasFilledTime0() bool {
	if o != nil && o.FilledTime0 != nil {
		return true
	}

	return false
}

// SetFilledTime0 gets a reference to the given float32 and assigns it to the FilledTime0 field.
func (o *GetOrdersItemOrders) SetFilledTime0(v float32) {
	o.FilledTime0 = &v
}

// GetFilledValue returns the FilledValue field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetFilledValue() string {
	if o == nil || o.FilledValue == nil {
		var ret string
		return ret
	}
	return *o.FilledValue
}

// GetFilledValueOk returns a tuple with the FilledValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetFilledValueOk() (*string, bool) {
	if o == nil || o.FilledValue == nil {
		return nil, false
	}
	return o.FilledValue, true
}

// HasFilledValue returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasFilledValue() bool {
	if o != nil && o.FilledValue != nil {
		return true
	}

	return false
}

// SetFilledValue gets a reference to the given string and assigns it to the FilledValue field.
func (o *GetOrdersItemOrders) SetFilledValue(v string) {
	o.FilledValue = &v
}

// GetOptionContractMultiplier returns the OptionContractMultiplier field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionContractMultiplier() string {
	if o == nil || o.OptionContractMultiplier == nil {
		var ret string
		return ret
	}
	return *o.OptionContractMultiplier
}

// GetOptionContractMultiplierOk returns a tuple with the OptionContractMultiplier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionContractMultiplierOk() (*string, bool) {
	if o == nil || o.OptionContractMultiplier == nil {
		return nil, false
	}
	return o.OptionContractMultiplier, true
}

// HasOptionContractMultiplier returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionContractMultiplier() bool {
	if o != nil && o.OptionContractMultiplier != nil {
		return true
	}

	return false
}

// SetOptionContractMultiplier gets a reference to the given string and assigns it to the OptionContractMultiplier field.
func (o *GetOrdersItemOrders) SetOptionContractMultiplier(v string) {
	o.OptionContractMultiplier = &v
}

// GetOptionExercisePrice returns the OptionExercisePrice field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionExercisePrice() string {
	if o == nil || o.OptionExercisePrice == nil {
		var ret string
		return ret
	}
	return *o.OptionExercisePrice
}

// GetOptionExercisePriceOk returns a tuple with the OptionExercisePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionExercisePriceOk() (*string, bool) {
	if o == nil || o.OptionExercisePrice == nil {
		return nil, false
	}
	return o.OptionExercisePrice, true
}

// HasOptionExercisePrice returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionExercisePrice() bool {
	if o != nil && o.OptionExercisePrice != nil {
		return true
	}

	return false
}

// SetOptionExercisePrice gets a reference to the given string and assigns it to the OptionExercisePrice field.
func (o *GetOrdersItemOrders) SetOptionExercisePrice(v string) {
	o.OptionExercisePrice = &v
}

// GetOptionCycle returns the OptionCycle field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionCycle() int64 {
	if o == nil || o.OptionCycle == nil {
		var ret int64
		return ret
	}
	return *o.OptionCycle
}

// GetOptionCycleOk returns a tuple with the OptionCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionCycleOk() (*int64, bool) {
	if o == nil || o.OptionCycle == nil {
		return nil, false
	}
	return o.OptionCycle, true
}

// HasOptionCycle returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionCycle() bool {
	if o != nil && o.OptionCycle != nil {
		return true
	}

	return false
}

// SetOptionCycle gets a reference to the given int64 and assigns it to the OptionCycle field.
func (o *GetOrdersItemOrders) SetOptionCycle(v int64) {
	o.OptionCycle = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOrderId() int32 {
	if o == nil || o.OrderId == nil {
		var ret int32
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOrderIdOk() (*int32, bool) {
	if o == nil || o.OrderId == nil {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOrderId() bool {
	if o != nil && o.OrderId != nil {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int32 and assigns it to the OrderId field.
func (o *GetOrdersItemOrders) SetOrderId(v int32) {
	o.OrderId = &v
}

// GetOrderType returns the OrderType field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOrderType() OrderType {
	if o == nil || o.OrderType == nil {
		var ret OrderType
		return ret
	}
	return *o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOrderTypeOk() (*OrderType, bool) {
	if o == nil || o.OrderType == nil {
		return nil, false
	}
	return o.OrderType, true
}

// HasOrderType returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOrderType() bool {
	if o != nil && o.OrderType != nil {
		return true
	}

	return false
}

// SetOrderType gets a reference to the given OrderType and assigns it to the OrderType field.
func (o *GetOrdersItemOrders) SetOrderType(v OrderType) {
	o.OrderType = &v
}

// GetOptionType returns the OptionType field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionType() OptionType {
	if o == nil || o.OptionType == nil {
		var ret OptionType
		return ret
	}
	return *o.OptionType
}

// GetOptionTypeOk returns a tuple with the OptionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionTypeOk() (*OptionType, bool) {
	if o == nil || o.OptionType == nil {
		return nil, false
	}
	return o.OptionType, true
}

// HasOptionType returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionType() bool {
	if o != nil && o.OptionType != nil {
		return true
	}

	return false
}

// SetOptionType gets a reference to the given OptionType and assigns it to the OptionType field.
func (o *GetOrdersItemOrders) SetOptionType(v OptionType) {
	o.OptionType = &v
}

// GetOptionExpirationDate returns the OptionExpirationDate field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionExpirationDate() string {
	if o == nil || o.OptionExpirationDate == nil {
		var ret string
		return ret
	}
	return *o.OptionExpirationDate
}

// GetOptionExpirationDateOk returns a tuple with the OptionExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionExpirationDateOk() (*string, bool) {
	if o == nil || o.OptionExpirationDate == nil {
		return nil, false
	}
	return o.OptionExpirationDate, true
}

// HasOptionExpirationDate returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionExpirationDate() bool {
	if o != nil && o.OptionExpirationDate != nil {
		return true
	}

	return false
}

// SetOptionExpirationDate gets a reference to the given string and assigns it to the OptionExpirationDate field.
func (o *GetOrdersItemOrders) SetOptionExpirationDate(v string) {
	o.OptionExpirationDate = &v
}

// GetRelation returns the Relation field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetRelation() string {
	if o == nil || o.Relation == nil {
		var ret string
		return ret
	}
	return *o.Relation
}

// GetRelationOk returns a tuple with the Relation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetRelationOk() (*string, bool) {
	if o == nil || o.Relation == nil {
		return nil, false
	}
	return o.Relation, true
}

// HasRelation returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasRelation() bool {
	if o != nil && o.Relation != nil {
		return true
	}

	return false
}

// SetRelation gets a reference to the given string and assigns it to the Relation field.
func (o *GetOrdersItemOrders) SetRelation(v string) {
	o.Relation = &v
}

// GetOptionCategory returns the OptionCategory field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetOptionCategory() string {
	if o == nil || o.OptionCategory == nil {
		var ret string
		return ret
	}
	return *o.OptionCategory
}

// GetOptionCategoryOk returns a tuple with the OptionCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetOptionCategoryOk() (*string, bool) {
	if o == nil || o.OptionCategory == nil {
		return nil, false
	}
	return o.OptionCategory, true
}

// HasOptionCategory returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasOptionCategory() bool {
	if o != nil && o.OptionCategory != nil {
		return true
	}

	return false
}

// SetOptionCategory gets a reference to the given string and assigns it to the OptionCategory field.
func (o *GetOrdersItemOrders) SetOptionCategory(v string) {
	o.OptionCategory = &v
}

// GetRemainQuantity returns the RemainQuantity field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetRemainQuantity() string {
	if o == nil || o.RemainQuantity == nil {
		var ret string
		return ret
	}
	return *o.RemainQuantity
}

// GetRemainQuantityOk returns a tuple with the RemainQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetRemainQuantityOk() (*string, bool) {
	if o == nil || o.RemainQuantity == nil {
		return nil, false
	}
	return o.RemainQuantity, true
}

// HasRemainQuantity returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasRemainQuantity() bool {
	if o != nil && o.RemainQuantity != nil {
		return true
	}

	return false
}

// SetRemainQuantity gets a reference to the given string and assigns it to the RemainQuantity field.
func (o *GetOrdersItemOrders) SetRemainQuantity(v string) {
	o.RemainQuantity = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetStatusCode() string {
	if o == nil || o.StatusCode == nil {
		var ret string
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetStatusCodeOk() (*string, bool) {
	if o == nil || o.StatusCode == nil {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasStatusCode() bool {
	if o != nil && o.StatusCode != nil {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given string and assigns it to the StatusCode field.
func (o *GetOrdersItemOrders) SetStatusCode(v string) {
	o.StatusCode = &v
}

// GetStatusStr returns the StatusStr field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetStatusStr() string {
	if o == nil || o.StatusStr == nil {
		var ret string
		return ret
	}
	return *o.StatusStr
}

// GetStatusStrOk returns a tuple with the StatusStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetStatusStrOk() (*string, bool) {
	if o == nil || o.StatusStr == nil {
		return nil, false
	}
	return o.StatusStr, true
}

// HasStatusStr returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasStatusStr() bool {
	if o != nil && o.StatusStr != nil {
		return true
	}

	return false
}

// SetStatusStr gets a reference to the given string and assigns it to the StatusStr field.
func (o *GetOrdersItemOrders) SetStatusStr(v string) {
	o.StatusStr = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *GetOrdersItemOrders) SetSymbol(v string) {
	o.Symbol = &v
}

// GetTicker returns the Ticker field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetTicker() GetOrdersItemTicker {
	if o == nil || o.Ticker == nil {
		var ret GetOrdersItemTicker
		return ret
	}
	return *o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetTickerOk() (*GetOrdersItemTicker, bool) {
	if o == nil || o.Ticker == nil {
		return nil, false
	}
	return o.Ticker, true
}

// HasTicker returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasTicker() bool {
	if o != nil && o.Ticker != nil {
		return true
	}

	return false
}

// SetTicker gets a reference to the given GetOrdersItemTicker and assigns it to the Ticker field.
func (o *GetOrdersItemOrders) SetTicker(v GetOrdersItemTicker) {
	o.Ticker = &v
}

// GetTickerId returns the TickerId field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetTickerId() int32 {
	if o == nil || o.TickerId == nil {
		var ret int32
		return ret
	}
	return *o.TickerId
}

// GetTickerIdOk returns a tuple with the TickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetTickerIdOk() (*int32, bool) {
	if o == nil || o.TickerId == nil {
		return nil, false
	}
	return o.TickerId, true
}

// HasTickerId returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasTickerId() bool {
	if o != nil && o.TickerId != nil {
		return true
	}

	return false
}

// SetTickerId gets a reference to the given int32 and assigns it to the TickerId field.
func (o *GetOrdersItemOrders) SetTickerId(v int32) {
	o.TickerId = &v
}

// GetTickerPriceDefineList returns the TickerPriceDefineList field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetTickerPriceDefineList() []GetOrdersItemTickerPriceDefineList {
	if o == nil || o.TickerPriceDefineList == nil {
		var ret []GetOrdersItemTickerPriceDefineList
		return ret
	}
	return *o.TickerPriceDefineList
}

// GetTickerPriceDefineListOk returns a tuple with the TickerPriceDefineList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetTickerPriceDefineListOk() (*[]GetOrdersItemTickerPriceDefineList, bool) {
	if o == nil || o.TickerPriceDefineList == nil {
		return nil, false
	}
	return o.TickerPriceDefineList, true
}

// HasTickerPriceDefineList returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasTickerPriceDefineList() bool {
	if o != nil && o.TickerPriceDefineList != nil {
		return true
	}

	return false
}

// SetTickerPriceDefineList gets a reference to the given []GetOrdersItemTickerPriceDefineList and assigns it to the TickerPriceDefineList field.
func (o *GetOrdersItemOrders) SetTickerPriceDefineList(v []GetOrdersItemTickerPriceDefineList) {
	o.TickerPriceDefineList = &v
}

// GetTimeInForce returns the TimeInForce field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetTimeInForce() TimeInForce {
	if o == nil || o.TimeInForce == nil {
		var ret TimeInForce
		return ret
	}
	return *o.TimeInForce
}

// GetTimeInForceOk returns a tuple with the TimeInForce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetTimeInForceOk() (*TimeInForce, bool) {
	if o == nil || o.TimeInForce == nil {
		return nil, false
	}
	return o.TimeInForce, true
}

// HasTimeInForce returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasTimeInForce() bool {
	if o != nil && o.TimeInForce != nil {
		return true
	}

	return false
}

// SetTimeInForce gets a reference to the given TimeInForce and assigns it to the TimeInForce field.
func (o *GetOrdersItemOrders) SetTimeInForce(v TimeInForce) {
	o.TimeInForce = &v
}

// GetTotalQuantity returns the TotalQuantity field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetTotalQuantity() string {
	if o == nil || o.TotalQuantity == nil {
		var ret string
		return ret
	}
	return *o.TotalQuantity
}

// GetTotalQuantityOk returns a tuple with the TotalQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetTotalQuantityOk() (*string, bool) {
	if o == nil || o.TotalQuantity == nil {
		return nil, false
	}
	return o.TotalQuantity, true
}

// HasTotalQuantity returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasTotalQuantity() bool {
	if o != nil && o.TotalQuantity != nil {
		return true
	}

	return false
}

// SetTotalQuantity gets a reference to the given string and assigns it to the TotalQuantity field.
func (o *GetOrdersItemOrders) SetTotalQuantity(v string) {
	o.TotalQuantity = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetUpdateTime() string {
	if o == nil || o.UpdateTime == nil {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetUpdateTimeOk() (*string, bool) {
	if o == nil || o.UpdateTime == nil {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasUpdateTime() bool {
	if o != nil && o.UpdateTime != nil {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *GetOrdersItemOrders) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

// GetUpdateTime0 returns the UpdateTime0 field value if set, zero value otherwise.
func (o *GetOrdersItemOrders) GetUpdateTime0() float32 {
	if o == nil || o.UpdateTime0 == nil {
		var ret float32
		return ret
	}
	return *o.UpdateTime0
}

// GetUpdateTime0Ok returns a tuple with the UpdateTime0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersItemOrders) GetUpdateTime0Ok() (*float32, bool) {
	if o == nil || o.UpdateTime0 == nil {
		return nil, false
	}
	return o.UpdateTime0, true
}

// HasUpdateTime0 returns a boolean if a field has been set.
func (o *GetOrdersItemOrders) HasUpdateTime0() bool {
	if o != nil && o.UpdateTime0 != nil {
		return true
	}

	return false
}

// SetUpdateTime0 gets a reference to the given float32 and assigns it to the UpdateTime0 field.
func (o *GetOrdersItemOrders) SetUpdateTime0(v float32) {
	o.UpdateTime0 = &v
}

func (o GetOrdersItemOrders) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.AssetType != nil {
		toSerialize["assetType"] = o.AssetType
	}
	if o.AvgFilledPrice != nil {
		toSerialize["avgFilledPrice"] = o.AvgFilledPrice
	}
	if o.BrokerId != nil {
		toSerialize["brokerId"] = o.BrokerId
	}
	if o.CanCancel != nil {
		toSerialize["canCancel"] = o.CanCancel
	}
	if o.CanModify != nil {
		toSerialize["canModify"] = o.CanModify
	}
	if o.CreateTime != nil {
		toSerialize["createTime"] = o.CreateTime
	}
	if o.CreateTime0 != nil {
		toSerialize["createTime0"] = o.CreateTime0
	}
	if o.FilledQuantity != nil {
		toSerialize["filledQuantity"] = o.FilledQuantity
	}
	if o.FilledTime != nil {
		toSerialize["filledTime"] = o.FilledTime
	}
	if o.FilledTime0 != nil {
		toSerialize["filledTime0"] = o.FilledTime0
	}
	if o.FilledValue != nil {
		toSerialize["filledValue"] = o.FilledValue
	}
	if o.OptionContractMultiplier != nil {
		toSerialize["optionContractMultiplier"] = o.OptionContractMultiplier
	}
	if o.OptionExercisePrice != nil {
		toSerialize["optionExercisePrice"] = o.OptionExercisePrice
	}
	if o.OptionCycle != nil {
		toSerialize["optionCycle"] = o.OptionCycle
	}
	if o.OrderId != nil {
		toSerialize["orderId"] = o.OrderId
	}
	if o.OrderType != nil {
		toSerialize["orderType"] = o.OrderType
	}
	if o.OptionType != nil {
		toSerialize["optionType"] = o.OptionType
	}
	if o.OptionExpirationDate != nil {
		toSerialize["optionExpirationDate"] = o.OptionExpirationDate
	}
	if o.Relation != nil {
		toSerialize["relation"] = o.Relation
	}
	if o.OptionCategory != nil {
		toSerialize["optionCategory"] = o.OptionCategory
	}
	if o.RemainQuantity != nil {
		toSerialize["remainQuantity"] = o.RemainQuantity
	}
	if o.StatusCode != nil {
		toSerialize["statusCode"] = o.StatusCode
	}
	if o.StatusStr != nil {
		toSerialize["statusStr"] = o.StatusStr
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Ticker != nil {
		toSerialize["ticker"] = o.Ticker
	}
	if o.TickerId != nil {
		toSerialize["tickerId"] = o.TickerId
	}
	if o.TickerPriceDefineList != nil {
		toSerialize["tickerPriceDefineList"] = o.TickerPriceDefineList
	}
	if o.TimeInForce != nil {
		toSerialize["timeInForce"] = o.TimeInForce
	}
	if o.TotalQuantity != nil {
		toSerialize["totalQuantity"] = o.TotalQuantity
	}
	if o.UpdateTime != nil {
		toSerialize["updateTime"] = o.UpdateTime
	}
	if o.UpdateTime0 != nil {
		toSerialize["updateTime0"] = o.UpdateTime0
	}
	return json.Marshal(toSerialize)
}

type NullableGetOrdersItemOrders struct {
	value *GetOrdersItemOrders
	isSet bool
}

func (v NullableGetOrdersItemOrders) Get() *GetOrdersItemOrders {
	return v.value
}

func (v *NullableGetOrdersItemOrders) Set(val *GetOrdersItemOrders) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrdersItemOrders) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrdersItemOrders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrdersItemOrders(val *GetOrdersItemOrders) *NullableGetOrdersItemOrders {
	return &NullableGetOrdersItemOrders{value: val, isSet: true}
}

func (v NullableGetOrdersItemOrders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrdersItemOrders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


