/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaperTradeOrder struct for PaperTradeOrder
type PaperTradeOrder struct {
	OrderId int32 `json:"orderId,omitempty"`
	PaperId int32 `json:"paperId,omitempty"`
	Action OrderSide `json:"action,omitempty"`
	TotalQuantity string `json:"totalQuantity,omitempty"`
	FilledQuantity string `json:"filledQuantity,omitempty"`
	PlacedTime string `json:"placedTime,omitempty"`
	TimeInForce TimeInForce `json:"timeInForce,omitempty"`
	OrderType OrderType `json:"orderType,omitempty"`
	LmtPrice string `json:"lmtPrice,omitempty"`
	Ticker PaperTradeOrderTicker `json:"ticker,omitempty"`
	CanModify bool `json:"canModify,omitempty"`
	CanCancel bool `json:"canCancel,omitempty"`
	CreateTime string `json:"createTime,omitempty"`
	CreateTime0 int64 `json:"createTime0,omitempty"`
	Status string `json:"status,omitempty"`
	StatusStr string `json:"statusStr,omitempty"`
	OutsideRegularTradingHour bool `json:"outsideRegularTradingHour,omitempty"`
}
