/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComboType the model 'ComboType'
type ComboType string

// List of ComboType
const (
	NORMAL ComboType = "NORMAL"
	MASTER ComboType = "MASTER"
	STOP_LOSS ComboType = "STOP_LOSS"
	STOP_PROFIT ComboType = "STOP_PROFIT"
	LMT ComboType = "LMT"
	MKT ComboType = "MKT"
)
